(function) @function
(type_alias) @type
(type_enum) @type
(type_struct) @type
(constant) @constant
(validator) @function.special
(test) @function.test
(benchmark) @function.test
(identifier) @variable
(discard) @variable.builtin
(type_identifier) @type
(string) @string
(int) @number
(bytes) @string.special
(any_comment) @comment
(comment) @comment
(decorator) @attribute
(bool) @constant.builtin
".." @punctuation.special
"use" @keyword
"pub" @keyword
"opaque" @keyword
"type" @keyword
"fn" @keyword
"validator" @keyword
"test" @keyword
"bench" @keyword
"const" @keyword
"let" @keyword
"expect" @keyword
"when" @keyword
"is" @keyword
"if" @keyword
"else" @keyword
"trace" @keyword
"fail" @keyword
"error" @keyword
"todo" @keyword
"as" @keyword
"via" @keyword
"and" @keyword
"or" @keyword
"once" @keyword
["!" "-" "+" "*" "/" "%" "==" "!=" "<" "<=" ">" ">=" "&&" "||" "|>" "->" "|" "<-" "?"] @operator
