#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 109
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 60
#define ALIAS_COUNT 0
#define TOKEN_COUNT 30
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 8

enum {
  anon_sym_use = 1,
  anon_sym_DOT = 2,
  anon_sym_as = 3,
  anon_sym_SLASH = 4,
  anon_sym_LBRACE = 5,
  anon_sym_COMMA = 6,
  anon_sym_RBRACE = 7,
  anon_sym_type = 8,
  anon_sym_EQ = 9,
  anon_sym_LPAREN = 10,
  anon_sym_RPAREN = 11,
  anon_sym_COLON = 12,
  anon_sym_LT = 13,
  anon_sym_GT = 14,
  anon_sym_const = 15,
  sym_base10 = 16,
  sym_base10_underscore = 17,
  sym_base16 = 18,
  anon_sym_AT = 19,
  anon_sym_POUND = 20,
  anon_sym_DQUOTE = 21,
  aux_sym_string_inner_token1 = 22,
  sym_escape = 23,
  sym_module_comment = 24,
  sym_definition_comment = 25,
  sym_comment = 26,
  sym__discard_name = 27,
  sym__name = 28,
  sym__upname = 29,
  sym_source_file = 30,
  sym__definition = 31,
  sym_import = 32,
  sym_module = 33,
  sym_unqualified_imports = 34,
  sym_unqualified_import = 35,
  sym_type_alias = 36,
  sym_type_enum = 37,
  sym_type_enum_variant = 38,
  sym_type_struct = 39,
  sym_type_struct_inner = 40,
  sym_type_struct_fields = 41,
  sym_type_struct_field = 42,
  sym_type_definition = 43,
  sym_type_argument = 44,
  sym_constant = 45,
  sym_constant_value = 46,
  sym_int = 47,
  sym_string = 48,
  sym_bytes = 49,
  sym_string_inner = 50,
  sym_identifier = 51,
  sym_type_identifier = 52,
  aux_sym_source_file_repeat1 = 53,
  aux_sym_module_repeat1 = 54,
  aux_sym_unqualified_imports_repeat1 = 55,
  aux_sym_type_enum_repeat1 = 56,
  aux_sym_type_enum_variant_repeat1 = 57,
  aux_sym_type_struct_fields_repeat1 = 58,
  aux_sym_string_inner_repeat1 = 59,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_use] = "use",
  [anon_sym_DOT] = ".",
  [anon_sym_as] = "as",
  [anon_sym_SLASH] = "/",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACE] = "}",
  [anon_sym_type] = "type",
  [anon_sym_EQ] = "=",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COLON] = ":",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_const] = "const",
  [sym_base10] = "base10",
  [sym_base10_underscore] = "base10_underscore",
  [sym_base16] = "base16",
  [anon_sym_AT] = "@",
  [anon_sym_POUND] = "#",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_inner_token1] = "string_inner_token1",
  [sym_escape] = "escape",
  [sym_module_comment] = "module_comment",
  [sym_definition_comment] = "definition_comment",
  [sym_comment] = "comment",
  [sym__discard_name] = "_discard_name",
  [sym__name] = "_name",
  [sym__upname] = "_upname",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_import] = "import",
  [sym_module] = "module",
  [sym_unqualified_imports] = "unqualified_imports",
  [sym_unqualified_import] = "unqualified_import",
  [sym_type_alias] = "type_alias",
  [sym_type_enum] = "type_enum",
  [sym_type_enum_variant] = "type_enum_variant",
  [sym_type_struct] = "type_struct",
  [sym_type_struct_inner] = "type_struct_inner",
  [sym_type_struct_fields] = "type_struct_fields",
  [sym_type_struct_field] = "type_struct_field",
  [sym_type_definition] = "type_definition",
  [sym_type_argument] = "type_argument",
  [sym_constant] = "constant",
  [sym_constant_value] = "constant_value",
  [sym_int] = "int",
  [sym_string] = "string",
  [sym_bytes] = "bytes",
  [sym_string_inner] = "string_inner",
  [sym_identifier] = "identifier",
  [sym_type_identifier] = "type_identifier",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_module_repeat1] = "module_repeat1",
  [aux_sym_unqualified_imports_repeat1] = "unqualified_imports_repeat1",
  [aux_sym_type_enum_repeat1] = "type_enum_repeat1",
  [aux_sym_type_enum_variant_repeat1] = "type_enum_variant_repeat1",
  [aux_sym_type_struct_fields_repeat1] = "type_struct_fields_repeat1",
  [aux_sym_string_inner_repeat1] = "string_inner_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_use] = anon_sym_use,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_as] = anon_sym_as,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_type] = anon_sym_type,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_const] = anon_sym_const,
  [sym_base10] = sym_base10,
  [sym_base10_underscore] = sym_base10_underscore,
  [sym_base16] = sym_base16,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_inner_token1] = aux_sym_string_inner_token1,
  [sym_escape] = sym_escape,
  [sym_module_comment] = sym_module_comment,
  [sym_definition_comment] = sym_definition_comment,
  [sym_comment] = sym_comment,
  [sym__discard_name] = sym__discard_name,
  [sym__name] = sym__name,
  [sym__upname] = sym__upname,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_import] = sym_import,
  [sym_module] = sym_module,
  [sym_unqualified_imports] = sym_unqualified_imports,
  [sym_unqualified_import] = sym_unqualified_import,
  [sym_type_alias] = sym_type_alias,
  [sym_type_enum] = sym_type_enum,
  [sym_type_enum_variant] = sym_type_enum_variant,
  [sym_type_struct] = sym_type_struct,
  [sym_type_struct_inner] = sym_type_struct_inner,
  [sym_type_struct_fields] = sym_type_struct_fields,
  [sym_type_struct_field] = sym_type_struct_field,
  [sym_type_definition] = sym_type_definition,
  [sym_type_argument] = sym_type_argument,
  [sym_constant] = sym_constant,
  [sym_constant_value] = sym_constant_value,
  [sym_int] = sym_int,
  [sym_string] = sym_string,
  [sym_bytes] = sym_bytes,
  [sym_string_inner] = sym_string_inner,
  [sym_identifier] = sym_identifier,
  [sym_type_identifier] = sym_type_identifier,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_module_repeat1] = aux_sym_module_repeat1,
  [aux_sym_unqualified_imports_repeat1] = aux_sym_unqualified_imports_repeat1,
  [aux_sym_type_enum_repeat1] = aux_sym_type_enum_repeat1,
  [aux_sym_type_enum_variant_repeat1] = aux_sym_type_enum_variant_repeat1,
  [aux_sym_type_struct_fields_repeat1] = aux_sym_type_struct_fields_repeat1,
  [aux_sym_string_inner_repeat1] = aux_sym_string_inner_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_use] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_const] = {
    .visible = true,
    .named = false,
  },
  [sym_base10] = {
    .visible = true,
    .named = true,
  },
  [sym_base10_underscore] = {
    .visible = true,
    .named = true,
  },
  [sym_base16] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_inner_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_escape] = {
    .visible = true,
    .named = true,
  },
  [sym_module_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_definition_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__discard_name] = {
    .visible = false,
    .named = true,
  },
  [sym__name] = {
    .visible = false,
    .named = true,
  },
  [sym__upname] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_import] = {
    .visible = true,
    .named = true,
  },
  [sym_module] = {
    .visible = true,
    .named = true,
  },
  [sym_unqualified_imports] = {
    .visible = true,
    .named = true,
  },
  [sym_unqualified_import] = {
    .visible = true,
    .named = true,
  },
  [sym_type_alias] = {
    .visible = true,
    .named = true,
  },
  [sym_type_enum] = {
    .visible = true,
    .named = true,
  },
  [sym_type_enum_variant] = {
    .visible = true,
    .named = true,
  },
  [sym_type_struct] = {
    .visible = true,
    .named = true,
  },
  [sym_type_struct_inner] = {
    .visible = true,
    .named = true,
  },
  [sym_type_struct_fields] = {
    .visible = true,
    .named = true,
  },
  [sym_type_struct_field] = {
    .visible = true,
    .named = true,
  },
  [sym_type_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_type_argument] = {
    .visible = true,
    .named = true,
  },
  [sym_constant] = {
    .visible = true,
    .named = true,
  },
  [sym_constant_value] = {
    .visible = true,
    .named = true,
  },
  [sym_int] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_bytes] = {
    .visible = true,
    .named = true,
  },
  [sym_string_inner] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_type_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_module_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_unqualified_imports_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_enum_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_enum_variant_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_struct_fields_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_inner_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_alias = 1,
  field_module = 2,
  field_name = 3,
  field_type_argument = 4,
  field_unqualified = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_alias] = "alias",
  [field_module] = "module",
  [field_name] = "name",
  [field_type_argument] = "type_argument",
  [field_unqualified] = "unqualified",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 1},
  [5] = {.index = 6, .length = 1},
  [6] = {.index = 7, .length = 3},
  [7] = {.index = 10, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_module, 1},
  [1] =
    {field_module, 1},
    {field_unqualified, 3},
  [3] =
    {field_alias, 3},
    {field_module, 1},
  [5] =
    {field_type_argument, 0},
  [6] =
    {field_name, 0},
  [7] =
    {field_alias, 5},
    {field_module, 1},
    {field_unqualified, 3},
  [10] =
    {field_alias, 2},
    {field_name, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 31,
  [37] = 37,
  [38] = 30,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 52,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 6,
  [69] = 2,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 71,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 67,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 8,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 5,
  [101] = 9,
  [102] = 7,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(16);
      if (lookahead == '"') ADVANCE(38);
      if (lookahead == '#') ADVANCE(37);
      if (lookahead == '(') ADVANCE(26);
      if (lookahead == ')') ADVANCE(27);
      if (lookahead == ',') ADVANCE(22);
      if (lookahead == '.') ADVANCE(18);
      if (lookahead == '/') ADVANCE(20);
      if (lookahead == '0') ADVANCE(32);
      if (lookahead == ':') ADVANCE(28);
      if (lookahead == '<') ADVANCE(29);
      if (lookahead == '=') ADVANCE(25);
      if (lookahead == '>') ADVANCE(30);
      if (lookahead == '@') ADVANCE(36);
      if (lookahead == '\\') ADVANCE(15);
      if (lookahead == '_') ADVANCE(47);
      if (lookahead == 'a') ADVANCE(8);
      if (lookahead == 'c') ADVANCE(6);
      if (lookahead == 't') ADVANCE(12);
      if (lookahead == 'u') ADVANCE(9);
      if (lookahead == '{') ADVANCE(21);
      if (lookahead == '}') ADVANCE(23);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(49);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(38);
      if (lookahead == '\\') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(40);
      if (lookahead != 0) ADVANCE(39);
      END_STATE();
    case 2:
      if (lookahead == ')') ADVANCE(27);
      if (lookahead == ',') ADVANCE(22);
      if (lookahead == '<') ADVANCE(29);
      if (lookahead == '>') ADVANCE(30);
      if (lookahead == '}') ADVANCE(23);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(49);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 3:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 4:
      if (lookahead == 'e') ADVANCE(24);
      END_STATE();
    case 5:
      if (lookahead == 'n') ADVANCE(10);
      END_STATE();
    case 6:
      if (lookahead == 'o') ADVANCE(5);
      END_STATE();
    case 7:
      if (lookahead == 'p') ADVANCE(4);
      END_STATE();
    case 8:
      if (lookahead == 's') ADVANCE(19);
      END_STATE();
    case 9:
      if (lookahead == 's') ADVANCE(3);
      END_STATE();
    case 10:
      if (lookahead == 's') ADVANCE(11);
      END_STATE();
    case 11:
      if (lookahead == 't') ADVANCE(31);
      END_STATE();
    case 12:
      if (lookahead == 'y') ADVANCE(7);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 14:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(35);
      END_STATE();
    case 15:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(41);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_use);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_as);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(45);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_type);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_const);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_base10);
      if (lookahead == '_') ADVANCE(13);
      if (lookahead == 'x') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_base10);
      if (lookahead == '_') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_base10_underscore);
      if (lookahead == '_') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_base16);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_string_inner_token1);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_string_inner_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(39);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_escape);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_module_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_definition_comment);
      if (lookahead == '/') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(44);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_definition_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '/') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(46);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym__discard_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym__name);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym__upname);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 2},
  [47] = {.lex_state = 2},
  [48] = {.lex_state = 2},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 2},
  [52] = {.lex_state = 2},
  [53] = {.lex_state = 2},
  [54] = {.lex_state = 2},
  [55] = {.lex_state = 2},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 2},
  [58] = {.lex_state = 2},
  [59] = {.lex_state = 2},
  [60] = {.lex_state = 1},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 1},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 2},
  [69] = {.lex_state = 2},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 2},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 2},
  [91] = {.lex_state = 2},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 2},
  [94] = {.lex_state = 2},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 2},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 2},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 2},
  [101] = {.lex_state = 2},
  [102] = {.lex_state = 2},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 2},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_use] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_type] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_const] = ACTIONS(1),
    [sym_base10] = ACTIONS(1),
    [sym_base10_underscore] = ACTIONS(1),
    [sym_base16] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_escape] = ACTIONS(1),
    [sym_module_comment] = ACTIONS(1),
    [sym_definition_comment] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym__discard_name] = ACTIONS(1),
    [sym__upname] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(106),
    [sym__definition] = STATE(3),
    [sym_import] = STATE(3),
    [sym_type_alias] = STATE(3),
    [sym_type_enum] = STATE(3),
    [sym_type_struct] = STATE(3),
    [sym_constant] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_use] = ACTIONS(5),
    [anon_sym_type] = ACTIONS(7),
    [anon_sym_const] = ACTIONS(9),
    [sym_module_comment] = ACTIONS(11),
    [sym_definition_comment] = ACTIONS(13),
    [sym_comment] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(17), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(15), 15,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_as,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_type,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_const,
      sym_module_comment,
      sym__upname,
  [22] = 7,
    ACTIONS(5), 1,
      anon_sym_use,
    ACTIONS(7), 1,
      anon_sym_type,
    ACTIONS(9), 1,
      anon_sym_const,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 1,
      sym_module_comment,
    ACTIONS(23), 2,
      sym_definition_comment,
      sym_comment,
    STATE(4), 7,
      sym__definition,
      sym_import,
      sym_type_alias,
      sym_type_enum,
      sym_type_struct,
      sym_constant,
      aux_sym_source_file_repeat1,
  [51] = 7,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    ACTIONS(27), 1,
      anon_sym_use,
    ACTIONS(30), 1,
      anon_sym_type,
    ACTIONS(33), 1,
      anon_sym_const,
    ACTIONS(36), 1,
      sym_module_comment,
    ACTIONS(39), 2,
      sym_definition_comment,
      sym_comment,
    STATE(4), 7,
      sym__definition,
      sym_import,
      sym_type_alias,
      sym_type_enum,
      sym_type_struct,
      sym_constant,
      aux_sym_source_file_repeat1,
  [80] = 2,
    ACTIONS(44), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(42), 12,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_as,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_type,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_GT,
      anon_sym_const,
      sym_module_comment,
  [99] = 3,
    ACTIONS(48), 1,
      anon_sym_LT,
    ACTIONS(50), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(46), 10,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_type,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_GT,
      anon_sym_const,
      sym_module_comment,
  [119] = 2,
    ACTIONS(54), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(52), 10,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_type,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_GT,
      anon_sym_const,
      sym_module_comment,
  [136] = 2,
    ACTIONS(58), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(56), 10,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_type,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_GT,
      anon_sym_const,
      sym_module_comment,
  [153] = 2,
    ACTIONS(62), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(60), 10,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_type,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_GT,
      anon_sym_const,
      sym_module_comment,
  [170] = 4,
    ACTIONS(66), 1,
      anon_sym_SLASH,
    STATE(12), 1,
      aux_sym_module_repeat1,
    ACTIONS(68), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(64), 7,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_DOT,
      anon_sym_as,
      anon_sym_type,
      anon_sym_const,
      sym_module_comment,
  [190] = 8,
    ACTIONS(70), 1,
      sym_base10,
    ACTIONS(74), 1,
      anon_sym_AT,
    ACTIONS(76), 1,
      anon_sym_POUND,
    ACTIONS(78), 1,
      anon_sym_DQUOTE,
    STATE(24), 1,
      sym_constant_value,
    STATE(42), 1,
      sym_string_inner,
    ACTIONS(72), 2,
      sym_base10_underscore,
      sym_base16,
    STATE(45), 3,
      sym_int,
      sym_string,
      sym_bytes,
  [218] = 4,
    ACTIONS(66), 1,
      anon_sym_SLASH,
    STATE(14), 1,
      aux_sym_module_repeat1,
    ACTIONS(82), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(80), 7,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_DOT,
      anon_sym_as,
      anon_sym_type,
      anon_sym_const,
      sym_module_comment,
  [238] = 9,
    ACTIONS(84), 1,
      sym__name,
    ACTIONS(86), 1,
      sym__upname,
    STATE(56), 1,
      sym_type_identifier,
    STATE(84), 1,
      sym_type_struct_inner,
    STATE(103), 1,
      sym_identifier,
    STATE(105), 1,
      sym_type_definition,
    STATE(107), 1,
      sym_type_struct_fields,
    STATE(35), 2,
      sym_type_enum_variant,
      aux_sym_type_enum_repeat1,
    STATE(55), 2,
      sym_type_struct_field,
      aux_sym_type_struct_fields_repeat1,
  [268] = 4,
    ACTIONS(90), 1,
      anon_sym_SLASH,
    STATE(14), 1,
      aux_sym_module_repeat1,
    ACTIONS(93), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(88), 7,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_DOT,
      anon_sym_as,
      anon_sym_type,
      anon_sym_const,
      sym_module_comment,
  [288] = 8,
    ACTIONS(70), 1,
      sym_base10,
    ACTIONS(74), 1,
      anon_sym_AT,
    ACTIONS(76), 1,
      anon_sym_POUND,
    ACTIONS(78), 1,
      anon_sym_DQUOTE,
    STATE(42), 1,
      sym_string_inner,
    STATE(44), 1,
      sym_constant_value,
    ACTIONS(72), 2,
      sym_base10_underscore,
      sym_base16,
    STATE(45), 3,
      sym_int,
      sym_string,
      sym_bytes,
  [316] = 2,
    ACTIONS(93), 3,
      anon_sym_SLASH,
      sym_definition_comment,
      sym_comment,
    ACTIONS(88), 7,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_DOT,
      anon_sym_as,
      anon_sym_type,
      anon_sym_const,
      sym_module_comment,
  [331] = 4,
    ACTIONS(97), 1,
      anon_sym_DOT,
    ACTIONS(99), 1,
      anon_sym_as,
    ACTIONS(101), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(95), 5,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_type,
      anon_sym_const,
      sym_module_comment,
  [349] = 2,
    ACTIONS(105), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(103), 7,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_RBRACE,
      anon_sym_type,
      anon_sym_const,
      sym_module_comment,
      sym__upname,
  [363] = 2,
    ACTIONS(109), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(107), 6,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_as,
      anon_sym_type,
      anon_sym_const,
      sym_module_comment,
  [376] = 2,
    ACTIONS(113), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(111), 6,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_as,
      anon_sym_type,
      anon_sym_const,
      sym_module_comment,
  [389] = 3,
    ACTIONS(117), 1,
      anon_sym_as,
    ACTIONS(119), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(115), 5,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_type,
      anon_sym_const,
      sym_module_comment,
  [404] = 2,
    ACTIONS(123), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(121), 6,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_as,
      anon_sym_type,
      anon_sym_const,
      sym_module_comment,
  [417] = 2,
    ACTIONS(127), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(125), 6,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_as,
      anon_sym_type,
      anon_sym_const,
      sym_module_comment,
  [430] = 2,
    ACTIONS(131), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(129), 5,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_type,
      anon_sym_const,
      sym_module_comment,
  [442] = 2,
    ACTIONS(135), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(133), 5,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_type,
      anon_sym_const,
      sym_module_comment,
  [454] = 6,
    ACTIONS(137), 1,
      anon_sym_RBRACE,
    ACTIONS(139), 1,
      sym__upname,
    STATE(56), 1,
      sym_type_identifier,
    STATE(84), 1,
      sym_type_struct_inner,
    STATE(105), 1,
      sym_type_definition,
    STATE(26), 2,
      sym_type_enum_variant,
      aux_sym_type_enum_repeat1,
  [474] = 2,
    ACTIONS(144), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(142), 5,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_type,
      anon_sym_const,
      sym_module_comment,
  [486] = 2,
    ACTIONS(148), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(146), 5,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_type,
      anon_sym_const,
      sym_module_comment,
  [498] = 2,
    ACTIONS(152), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(150), 5,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_type,
      anon_sym_const,
      sym_module_comment,
  [510] = 6,
    ACTIONS(84), 1,
      sym__name,
    ACTIONS(86), 1,
      sym__upname,
    ACTIONS(154), 1,
      anon_sym_GT,
    STATE(6), 1,
      sym_type_identifier,
    STATE(77), 1,
      sym_type_argument,
    STATE(54), 2,
      sym_type_definition,
      sym_identifier,
  [530] = 6,
    ACTIONS(84), 1,
      sym__name,
    ACTIONS(86), 1,
      sym__upname,
    ACTIONS(156), 1,
      anon_sym_GT,
    STATE(6), 1,
      sym_type_identifier,
    STATE(77), 1,
      sym_type_argument,
    STATE(54), 2,
      sym_type_definition,
      sym_identifier,
  [550] = 6,
    ACTIONS(84), 1,
      sym__name,
    ACTIONS(86), 1,
      sym__upname,
    ACTIONS(158), 1,
      anon_sym_RPAREN,
    STATE(6), 1,
      sym_type_identifier,
    STATE(77), 1,
      sym_type_argument,
    STATE(54), 2,
      sym_type_definition,
      sym_identifier,
  [570] = 2,
    ACTIONS(162), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(160), 5,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_type,
      anon_sym_const,
      sym_module_comment,
  [582] = 2,
    ACTIONS(166), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(164), 5,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_type,
      anon_sym_const,
      sym_module_comment,
  [594] = 6,
    ACTIONS(86), 1,
      sym__upname,
    ACTIONS(168), 1,
      anon_sym_RBRACE,
    STATE(56), 1,
      sym_type_identifier,
    STATE(84), 1,
      sym_type_struct_inner,
    STATE(105), 1,
      sym_type_definition,
    STATE(26), 2,
      sym_type_enum_variant,
      aux_sym_type_enum_repeat1,
  [614] = 6,
    ACTIONS(84), 1,
      sym__name,
    ACTIONS(86), 1,
      sym__upname,
    ACTIONS(170), 1,
      anon_sym_GT,
    STATE(6), 1,
      sym_type_identifier,
    STATE(77), 1,
      sym_type_argument,
    STATE(54), 2,
      sym_type_definition,
      sym_identifier,
  [634] = 2,
    ACTIONS(174), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(172), 5,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_type,
      anon_sym_const,
      sym_module_comment,
  [646] = 6,
    ACTIONS(84), 1,
      sym__name,
    ACTIONS(86), 1,
      sym__upname,
    ACTIONS(176), 1,
      anon_sym_GT,
    STATE(6), 1,
      sym_type_identifier,
    STATE(77), 1,
      sym_type_argument,
    STATE(54), 2,
      sym_type_definition,
      sym_identifier,
  [666] = 2,
    ACTIONS(180), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(178), 5,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_type,
      anon_sym_const,
      sym_module_comment,
  [678] = 2,
    ACTIONS(184), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(182), 5,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_type,
      anon_sym_const,
      sym_module_comment,
  [690] = 6,
    ACTIONS(84), 1,
      sym__name,
    ACTIONS(86), 1,
      sym__upname,
    ACTIONS(186), 1,
      anon_sym_RPAREN,
    STATE(6), 1,
      sym_type_identifier,
    STATE(77), 1,
      sym_type_argument,
    STATE(54), 2,
      sym_type_definition,
      sym_identifier,
  [710] = 2,
    ACTIONS(190), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(188), 5,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_type,
      anon_sym_const,
      sym_module_comment,
  [722] = 2,
    ACTIONS(194), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(192), 5,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_type,
      anon_sym_const,
      sym_module_comment,
  [734] = 2,
    ACTIONS(198), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(196), 5,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_type,
      anon_sym_const,
      sym_module_comment,
  [746] = 2,
    ACTIONS(202), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(200), 5,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_type,
      anon_sym_const,
      sym_module_comment,
  [758] = 6,
    ACTIONS(84), 1,
      sym__name,
    ACTIONS(86), 1,
      sym__upname,
    ACTIONS(204), 1,
      anon_sym_RBRACE,
    STATE(65), 1,
      sym_identifier,
    STATE(73), 1,
      sym_type_identifier,
    STATE(86), 1,
      sym_unqualified_import,
  [777] = 5,
    ACTIONS(84), 1,
      sym__name,
    ACTIONS(86), 1,
      sym__upname,
    STATE(6), 1,
      sym_type_identifier,
    STATE(77), 1,
      sym_type_argument,
    STATE(54), 2,
      sym_type_definition,
      sym_identifier,
  [794] = 6,
    ACTIONS(84), 1,
      sym__name,
    ACTIONS(86), 1,
      sym__upname,
    ACTIONS(206), 1,
      anon_sym_RBRACE,
    STATE(65), 1,
      sym_identifier,
    STATE(73), 1,
      sym_type_identifier,
    STATE(86), 1,
      sym_unqualified_import,
  [813] = 6,
    ACTIONS(84), 1,
      sym__name,
    ACTIONS(86), 1,
      sym__upname,
    ACTIONS(208), 1,
      anon_sym_RBRACE,
    STATE(65), 1,
      sym_identifier,
    STATE(73), 1,
      sym_type_identifier,
    STATE(78), 1,
      sym_unqualified_import,
  [832] = 5,
    ACTIONS(210), 1,
      sym__name,
    ACTIONS(212), 1,
      sym__upname,
    STATE(68), 1,
      sym_type_identifier,
    STATE(90), 1,
      sym_type_argument,
    STATE(54), 2,
      sym_type_definition,
      sym_identifier,
  [849] = 5,
    ACTIONS(84), 1,
      sym__name,
    ACTIONS(86), 1,
      sym__upname,
    STATE(6), 1,
      sym_type_identifier,
    STATE(75), 1,
      sym_type_argument,
    STATE(54), 2,
      sym_type_definition,
      sym_identifier,
  [866] = 5,
    ACTIONS(84), 1,
      sym__name,
    ACTIONS(86), 1,
      sym__upname,
    STATE(6), 1,
      sym_type_identifier,
    STATE(74), 1,
      sym_type_argument,
    STATE(54), 2,
      sym_type_definition,
      sym_identifier,
  [883] = 5,
    ACTIONS(84), 1,
      sym__name,
    ACTIONS(86), 1,
      sym__upname,
    STATE(6), 1,
      sym_type_identifier,
    STATE(71), 1,
      sym_type_argument,
    STATE(54), 2,
      sym_type_definition,
      sym_identifier,
  [900] = 1,
    ACTIONS(214), 5,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_GT,
      sym__name,
  [908] = 4,
    ACTIONS(84), 1,
      sym__name,
    ACTIONS(216), 1,
      anon_sym_RBRACE,
    STATE(103), 1,
      sym_identifier,
    STATE(59), 2,
      sym_type_struct_field,
      aux_sym_type_struct_fields_repeat1,
  [922] = 4,
    ACTIONS(46), 1,
      anon_sym_LBRACE,
    ACTIONS(48), 1,
      anon_sym_LT,
    ACTIONS(220), 1,
      anon_sym_LPAREN,
    ACTIONS(218), 2,
      anon_sym_RBRACE,
      sym__upname,
  [936] = 5,
    ACTIONS(84), 1,
      sym__name,
    ACTIONS(86), 1,
      sym__upname,
    STATE(65), 1,
      sym_identifier,
    STATE(73), 1,
      sym_type_identifier,
    STATE(86), 1,
      sym_unqualified_import,
  [952] = 4,
    ACTIONS(84), 1,
      sym__name,
    STATE(103), 1,
      sym_identifier,
    STATE(107), 1,
      sym_type_struct_fields,
    STATE(55), 2,
      sym_type_struct_field,
      aux_sym_type_struct_fields_repeat1,
  [966] = 4,
    ACTIONS(222), 1,
      anon_sym_RBRACE,
    ACTIONS(224), 1,
      sym__name,
    STATE(103), 1,
      sym_identifier,
    STATE(59), 2,
      sym_type_struct_field,
      aux_sym_type_struct_fields_repeat1,
  [980] = 4,
    ACTIONS(227), 1,
      anon_sym_DQUOTE,
    ACTIONS(229), 1,
      aux_sym_string_inner_token1,
    ACTIONS(231), 1,
      sym_escape,
    STATE(64), 1,
      aux_sym_string_inner_repeat1,
  [993] = 3,
    ACTIONS(233), 1,
      anon_sym_COMMA,
    STATE(61), 1,
      aux_sym_type_enum_variant_repeat1,
    ACTIONS(236), 2,
      anon_sym_RPAREN,
      anon_sym_GT,
  [1004] = 4,
    ACTIONS(86), 1,
      sym__upname,
    STATE(6), 1,
      sym_type_identifier,
    STATE(43), 1,
      sym_type_struct_inner,
    STATE(81), 1,
      sym_type_definition,
  [1017] = 4,
    ACTIONS(238), 1,
      anon_sym_DQUOTE,
    ACTIONS(240), 1,
      aux_sym_string_inner_token1,
    ACTIONS(242), 1,
      sym_escape,
    STATE(60), 1,
      aux_sym_string_inner_repeat1,
  [1030] = 4,
    ACTIONS(244), 1,
      anon_sym_DQUOTE,
    ACTIONS(246), 1,
      aux_sym_string_inner_token1,
    ACTIONS(249), 1,
      sym_escape,
    STATE(64), 1,
      aux_sym_string_inner_repeat1,
  [1043] = 2,
    ACTIONS(252), 1,
      anon_sym_as,
    ACTIONS(254), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1051] = 3,
    ACTIONS(256), 1,
      anon_sym_COMMA,
    ACTIONS(259), 1,
      anon_sym_RBRACE,
    STATE(66), 1,
      aux_sym_unqualified_imports_repeat1,
  [1061] = 3,
    ACTIONS(156), 1,
      anon_sym_GT,
    ACTIONS(261), 1,
      anon_sym_COMMA,
    STATE(61), 1,
      aux_sym_type_enum_variant_repeat1,
  [1071] = 2,
    ACTIONS(263), 1,
      anon_sym_LT,
    ACTIONS(46), 2,
      anon_sym_RBRACE,
      sym__name,
  [1079] = 1,
    ACTIONS(15), 3,
      anon_sym_RBRACE,
      anon_sym_LT,
      sym__name,
  [1085] = 3,
    ACTIONS(206), 1,
      anon_sym_RBRACE,
    ACTIONS(265), 1,
      anon_sym_COMMA,
    STATE(66), 1,
      aux_sym_unqualified_imports_repeat1,
  [1095] = 3,
    ACTIONS(267), 1,
      anon_sym_COMMA,
    ACTIONS(269), 1,
      anon_sym_GT,
    STATE(79), 1,
      aux_sym_type_enum_variant_repeat1,
  [1105] = 3,
    ACTIONS(186), 1,
      anon_sym_RPAREN,
    ACTIONS(271), 1,
      anon_sym_COMMA,
    STATE(61), 1,
      aux_sym_type_enum_variant_repeat1,
  [1115] = 2,
    ACTIONS(273), 1,
      anon_sym_as,
    ACTIONS(254), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1123] = 3,
    ACTIONS(275), 1,
      anon_sym_COMMA,
    ACTIONS(277), 1,
      anon_sym_GT,
    STATE(67), 1,
      aux_sym_type_enum_variant_repeat1,
  [1133] = 3,
    ACTIONS(279), 1,
      anon_sym_COMMA,
    ACTIONS(281), 1,
      anon_sym_RPAREN,
    STATE(72), 1,
      aux_sym_type_enum_variant_repeat1,
  [1143] = 3,
    ACTIONS(86), 1,
      sym__upname,
    STATE(6), 1,
      sym_type_identifier,
    STATE(37), 1,
      sym_type_definition,
  [1153] = 1,
    ACTIONS(236), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_GT,
  [1159] = 3,
    ACTIONS(283), 1,
      anon_sym_COMMA,
    ACTIONS(285), 1,
      anon_sym_RBRACE,
    STATE(70), 1,
      aux_sym_unqualified_imports_repeat1,
  [1169] = 3,
    ACTIONS(170), 1,
      anon_sym_GT,
    ACTIONS(287), 1,
      anon_sym_COMMA,
    STATE(61), 1,
      aux_sym_type_enum_variant_repeat1,
  [1179] = 3,
    ACTIONS(86), 1,
      sym__upname,
    STATE(6), 1,
      sym_type_identifier,
    STATE(108), 1,
      sym_type_definition,
  [1189] = 2,
    ACTIONS(289), 1,
      anon_sym_LBRACE,
    ACTIONS(291), 1,
      anon_sym_EQ,
  [1196] = 2,
    ACTIONS(86), 1,
      sym__upname,
    STATE(87), 1,
      sym_type_identifier,
  [1203] = 2,
    ACTIONS(293), 1,
      sym__name,
    STATE(17), 1,
      sym_module,
  [1210] = 1,
    ACTIONS(218), 2,
      anon_sym_RBRACE,
      sym__upname,
  [1215] = 2,
    ACTIONS(295), 1,
      anon_sym_LBRACE,
    STATE(21), 1,
      sym_unqualified_imports,
  [1222] = 1,
    ACTIONS(259), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1227] = 1,
    ACTIONS(297), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1232] = 2,
    ACTIONS(78), 1,
      anon_sym_DQUOTE,
    STATE(34), 1,
      sym_string_inner,
  [1239] = 1,
    ACTIONS(299), 2,
      anon_sym_RBRACE,
      sym__upname,
  [1244] = 1,
    ACTIONS(301), 2,
      anon_sym_RBRACE,
      sym__name,
  [1249] = 2,
    ACTIONS(84), 1,
      sym__name,
    STATE(99), 1,
      sym_identifier,
  [1256] = 2,
    ACTIONS(78), 1,
      anon_sym_DQUOTE,
    STATE(28), 1,
      sym_string_inner,
  [1263] = 2,
    ACTIONS(84), 1,
      sym__name,
    STATE(29), 1,
      sym_identifier,
  [1270] = 2,
    ACTIONS(84), 1,
      sym__name,
    STATE(25), 1,
      sym_identifier,
  [1277] = 1,
    ACTIONS(303), 2,
      anon_sym_RBRACE,
      sym__upname,
  [1282] = 1,
    ACTIONS(56), 2,
      anon_sym_RBRACE,
      sym__name,
  [1287] = 1,
    ACTIONS(305), 2,
      anon_sym_RBRACE,
      sym__upname,
  [1292] = 2,
    ACTIONS(84), 1,
      sym__name,
    STATE(87), 1,
      sym_identifier,
  [1299] = 2,
    ACTIONS(307), 1,
      anon_sym_EQ,
    ACTIONS(309), 1,
      anon_sym_COLON,
  [1306] = 1,
    ACTIONS(42), 2,
      anon_sym_RBRACE,
      sym__name,
  [1311] = 1,
    ACTIONS(60), 2,
      anon_sym_RBRACE,
      sym__name,
  [1316] = 1,
    ACTIONS(52), 2,
      anon_sym_RBRACE,
      sym__name,
  [1321] = 1,
    ACTIONS(311), 1,
      anon_sym_COLON,
  [1325] = 1,
    ACTIONS(313), 1,
      sym__name,
  [1329] = 1,
    ACTIONS(315), 1,
      anon_sym_LBRACE,
  [1333] = 1,
    ACTIONS(317), 1,
      ts_builtin_sym_end,
  [1337] = 1,
    ACTIONS(319), 1,
      anon_sym_RBRACE,
  [1341] = 1,
    ACTIONS(321), 1,
      anon_sym_EQ,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 22,
  [SMALL_STATE(4)] = 51,
  [SMALL_STATE(5)] = 80,
  [SMALL_STATE(6)] = 99,
  [SMALL_STATE(7)] = 119,
  [SMALL_STATE(8)] = 136,
  [SMALL_STATE(9)] = 153,
  [SMALL_STATE(10)] = 170,
  [SMALL_STATE(11)] = 190,
  [SMALL_STATE(12)] = 218,
  [SMALL_STATE(13)] = 238,
  [SMALL_STATE(14)] = 268,
  [SMALL_STATE(15)] = 288,
  [SMALL_STATE(16)] = 316,
  [SMALL_STATE(17)] = 331,
  [SMALL_STATE(18)] = 349,
  [SMALL_STATE(19)] = 363,
  [SMALL_STATE(20)] = 376,
  [SMALL_STATE(21)] = 389,
  [SMALL_STATE(22)] = 404,
  [SMALL_STATE(23)] = 417,
  [SMALL_STATE(24)] = 430,
  [SMALL_STATE(25)] = 442,
  [SMALL_STATE(26)] = 454,
  [SMALL_STATE(27)] = 474,
  [SMALL_STATE(28)] = 486,
  [SMALL_STATE(29)] = 498,
  [SMALL_STATE(30)] = 510,
  [SMALL_STATE(31)] = 530,
  [SMALL_STATE(32)] = 550,
  [SMALL_STATE(33)] = 570,
  [SMALL_STATE(34)] = 582,
  [SMALL_STATE(35)] = 594,
  [SMALL_STATE(36)] = 614,
  [SMALL_STATE(37)] = 634,
  [SMALL_STATE(38)] = 646,
  [SMALL_STATE(39)] = 666,
  [SMALL_STATE(40)] = 678,
  [SMALL_STATE(41)] = 690,
  [SMALL_STATE(42)] = 710,
  [SMALL_STATE(43)] = 722,
  [SMALL_STATE(44)] = 734,
  [SMALL_STATE(45)] = 746,
  [SMALL_STATE(46)] = 758,
  [SMALL_STATE(47)] = 777,
  [SMALL_STATE(48)] = 794,
  [SMALL_STATE(49)] = 813,
  [SMALL_STATE(50)] = 832,
  [SMALL_STATE(51)] = 849,
  [SMALL_STATE(52)] = 866,
  [SMALL_STATE(53)] = 883,
  [SMALL_STATE(54)] = 900,
  [SMALL_STATE(55)] = 908,
  [SMALL_STATE(56)] = 922,
  [SMALL_STATE(57)] = 936,
  [SMALL_STATE(58)] = 952,
  [SMALL_STATE(59)] = 966,
  [SMALL_STATE(60)] = 980,
  [SMALL_STATE(61)] = 993,
  [SMALL_STATE(62)] = 1004,
  [SMALL_STATE(63)] = 1017,
  [SMALL_STATE(64)] = 1030,
  [SMALL_STATE(65)] = 1043,
  [SMALL_STATE(66)] = 1051,
  [SMALL_STATE(67)] = 1061,
  [SMALL_STATE(68)] = 1071,
  [SMALL_STATE(69)] = 1079,
  [SMALL_STATE(70)] = 1085,
  [SMALL_STATE(71)] = 1095,
  [SMALL_STATE(72)] = 1105,
  [SMALL_STATE(73)] = 1115,
  [SMALL_STATE(74)] = 1123,
  [SMALL_STATE(75)] = 1133,
  [SMALL_STATE(76)] = 1143,
  [SMALL_STATE(77)] = 1153,
  [SMALL_STATE(78)] = 1159,
  [SMALL_STATE(79)] = 1169,
  [SMALL_STATE(80)] = 1179,
  [SMALL_STATE(81)] = 1189,
  [SMALL_STATE(82)] = 1196,
  [SMALL_STATE(83)] = 1203,
  [SMALL_STATE(84)] = 1210,
  [SMALL_STATE(85)] = 1215,
  [SMALL_STATE(86)] = 1222,
  [SMALL_STATE(87)] = 1227,
  [SMALL_STATE(88)] = 1232,
  [SMALL_STATE(89)] = 1239,
  [SMALL_STATE(90)] = 1244,
  [SMALL_STATE(91)] = 1249,
  [SMALL_STATE(92)] = 1256,
  [SMALL_STATE(93)] = 1263,
  [SMALL_STATE(94)] = 1270,
  [SMALL_STATE(95)] = 1277,
  [SMALL_STATE(96)] = 1282,
  [SMALL_STATE(97)] = 1287,
  [SMALL_STATE(98)] = 1292,
  [SMALL_STATE(99)] = 1299,
  [SMALL_STATE(100)] = 1306,
  [SMALL_STATE(101)] = 1311,
  [SMALL_STATE(102)] = 1316,
  [SMALL_STATE(103)] = 1321,
  [SMALL_STATE(104)] = 1325,
  [SMALL_STATE(105)] = 1329,
  [SMALL_STATE(106)] = 1333,
  [SMALL_STATE(107)] = 1337,
  [SMALL_STATE(108)] = 1341,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_identifier, 1),
  [17] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_identifier, 1),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(83),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(62),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(91),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(4),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(4),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1),
  [44] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_identifier, 1),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_definition, 1),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_definition, 1),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_definition, 5),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_definition, 5),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_definition, 6),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_definition, 6),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_definition, 4),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_definition, 4),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module, 1),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(104),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_module, 1),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module, 2),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_module, 2),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_module_repeat1, 2),
  [90] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_module_repeat1, 2), SHIFT_REPEAT(104),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_module_repeat1, 2),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 2, .production_id = 1),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import, 2, .production_id = 1),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_struct_inner, 4),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_struct_inner, 4),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unqualified_imports, 5),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unqualified_imports, 5),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unqualified_imports, 3),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unqualified_imports, 3),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 4, .production_id = 2),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import, 4, .production_id = 2),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unqualified_imports, 4),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unqualified_imports, 4),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unqualified_imports, 2),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unqualified_imports, 2),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constant, 6),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_constant, 6),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 6, .production_id = 6),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import, 6, .production_id = 6),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_enum_repeat1, 2),
  [139] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_enum_repeat1, 2), SHIFT_REPEAT(2),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_enum, 5),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_enum, 5),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 4, .production_id = 3),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import, 4, .production_id = 3),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_inner, 2),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_inner, 2),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bytes, 2),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bytes, 2),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_alias, 4),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_alias, 4),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_inner, 3),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_inner, 3),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_int, 1),
  [184] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_int, 1),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bytes, 1),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bytes, 1),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_struct, 2),
  [194] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_struct, 2),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constant, 4),
  [198] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_constant, 4),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constant_value, 1),
  [202] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_constant_value, 1),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_argument, 1, .production_id = 4),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_struct_fields, 1),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_enum_variant, 1),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_struct_fields_repeat1, 2),
  [224] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_struct_fields_repeat1, 2), SHIFT_REPEAT(5),
  [227] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [231] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [233] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_enum_variant_repeat1, 2), SHIFT_REPEAT(47),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_enum_variant_repeat1, 2),
  [238] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [242] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [244] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_inner_repeat1, 2),
  [246] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_inner_repeat1, 2), SHIFT_REPEAT(64),
  [249] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_inner_repeat1, 2), SHIFT_REPEAT(64),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unqualified_import, 1, .production_id = 5),
  [256] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_unqualified_imports_repeat1, 2), SHIFT_REPEAT(57),
  [259] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_unqualified_imports_repeat1, 2),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [297] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unqualified_import, 3, .production_id = 7),
  [299] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_enum_variant, 4),
  [301] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_struct_field, 3),
  [303] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_enum_variant, 5),
  [305] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_enum_variant, 6),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [317] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_aiken(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
