#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 73
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 38
#define ALIAS_COUNT 0
#define TOKEN_COUNT 19
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 8

enum {
  anon_sym_use = 1,
  anon_sym_DOT = 2,
  anon_sym_as = 3,
  anon_sym_SLASH = 4,
  anon_sym_LBRACE = 5,
  anon_sym_COMMA = 6,
  anon_sym_RBRACE = 7,
  anon_sym_type = 8,
  anon_sym_EQ = 9,
  anon_sym_COLON = 10,
  anon_sym_LT = 11,
  anon_sym_GT = 12,
  sym_module_comment = 13,
  sym_definition_comment = 14,
  sym_comment = 15,
  sym__discard_name = 16,
  sym__name = 17,
  sym__upname = 18,
  sym_source_file = 19,
  sym__definition = 20,
  sym_import = 21,
  sym_module = 22,
  sym_unqualified_imports = 23,
  sym_unqualified_import = 24,
  sym_type_alias = 25,
  sym_type_struct = 26,
  sym_type_struct_fields = 27,
  sym_type_struct_field = 28,
  sym_type_definition = 29,
  sym_type_argument = 30,
  sym_identifier = 31,
  sym_type_identifier = 32,
  aux_sym_source_file_repeat1 = 33,
  aux_sym_module_repeat1 = 34,
  aux_sym_unqualified_imports_repeat1 = 35,
  aux_sym_type_struct_fields_repeat1 = 36,
  aux_sym_type_definition_repeat1 = 37,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_use] = "use",
  [anon_sym_DOT] = ".",
  [anon_sym_as] = "as",
  [anon_sym_SLASH] = "/",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACE] = "}",
  [anon_sym_type] = "type",
  [anon_sym_EQ] = "=",
  [anon_sym_COLON] = ":",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [sym_module_comment] = "module_comment",
  [sym_definition_comment] = "definition_comment",
  [sym_comment] = "comment",
  [sym__discard_name] = "_discard_name",
  [sym__name] = "_name",
  [sym__upname] = "_upname",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_import] = "import",
  [sym_module] = "module",
  [sym_unqualified_imports] = "unqualified_imports",
  [sym_unqualified_import] = "unqualified_import",
  [sym_type_alias] = "type_alias",
  [sym_type_struct] = "type_struct",
  [sym_type_struct_fields] = "type_struct_fields",
  [sym_type_struct_field] = "type_struct_field",
  [sym_type_definition] = "type_definition",
  [sym_type_argument] = "type_argument",
  [sym_identifier] = "identifier",
  [sym_type_identifier] = "type_identifier",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_module_repeat1] = "module_repeat1",
  [aux_sym_unqualified_imports_repeat1] = "unqualified_imports_repeat1",
  [aux_sym_type_struct_fields_repeat1] = "type_struct_fields_repeat1",
  [aux_sym_type_definition_repeat1] = "type_definition_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_use] = anon_sym_use,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_as] = anon_sym_as,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_type] = anon_sym_type,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [sym_module_comment] = sym_module_comment,
  [sym_definition_comment] = sym_definition_comment,
  [sym_comment] = sym_comment,
  [sym__discard_name] = sym__discard_name,
  [sym__name] = sym__name,
  [sym__upname] = sym__upname,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_import] = sym_import,
  [sym_module] = sym_module,
  [sym_unqualified_imports] = sym_unqualified_imports,
  [sym_unqualified_import] = sym_unqualified_import,
  [sym_type_alias] = sym_type_alias,
  [sym_type_struct] = sym_type_struct,
  [sym_type_struct_fields] = sym_type_struct_fields,
  [sym_type_struct_field] = sym_type_struct_field,
  [sym_type_definition] = sym_type_definition,
  [sym_type_argument] = sym_type_argument,
  [sym_identifier] = sym_identifier,
  [sym_type_identifier] = sym_type_identifier,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_module_repeat1] = aux_sym_module_repeat1,
  [aux_sym_unqualified_imports_repeat1] = aux_sym_unqualified_imports_repeat1,
  [aux_sym_type_struct_fields_repeat1] = aux_sym_type_struct_fields_repeat1,
  [aux_sym_type_definition_repeat1] = aux_sym_type_definition_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_use] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_module_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_definition_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__discard_name] = {
    .visible = false,
    .named = true,
  },
  [sym__name] = {
    .visible = false,
    .named = true,
  },
  [sym__upname] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_import] = {
    .visible = true,
    .named = true,
  },
  [sym_module] = {
    .visible = true,
    .named = true,
  },
  [sym_unqualified_imports] = {
    .visible = true,
    .named = true,
  },
  [sym_unqualified_import] = {
    .visible = true,
    .named = true,
  },
  [sym_type_alias] = {
    .visible = true,
    .named = true,
  },
  [sym_type_struct] = {
    .visible = true,
    .named = true,
  },
  [sym_type_struct_fields] = {
    .visible = true,
    .named = true,
  },
  [sym_type_struct_field] = {
    .visible = true,
    .named = true,
  },
  [sym_type_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_type_argument] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_type_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_module_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_unqualified_imports_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_struct_fields_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_alias = 1,
  field_module = 2,
  field_name = 3,
  field_type_argument = 4,
  field_unqualified = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_alias] = "alias",
  [field_module] = "module",
  [field_name] = "name",
  [field_type_argument] = "type_argument",
  [field_unqualified] = "unqualified",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 1},
  [5] = {.index = 6, .length = 1},
  [6] = {.index = 7, .length = 3},
  [7] = {.index = 10, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_module, 1},
  [1] =
    {field_module, 1},
    {field_unqualified, 3},
  [3] =
    {field_alias, 3},
    {field_module, 1},
  [5] =
    {field_type_argument, 0},
  [6] =
    {field_name, 0},
  [7] =
    {field_alias, 5},
    {field_module, 1},
    {field_unqualified, 3},
  [10] =
    {field_alias, 2},
    {field_name, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 17,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 18,
  [24] = 24,
  [25] = 25,
  [26] = 25,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 5,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 43,
  [47] = 47,
  [48] = 47,
  [49] = 49,
  [50] = 2,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 3,
  [63] = 7,
  [64] = 12,
  [65] = 10,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      if (lookahead == ',') ADVANCE(14);
      if (lookahead == '.') ADVANCE(10);
      if (lookahead == '/') ADVANCE(12);
      if (lookahead == ':') ADVANCE(18);
      if (lookahead == '<') ADVANCE(19);
      if (lookahead == '=') ADVANCE(17);
      if (lookahead == '>') ADVANCE(20);
      if (lookahead == '_') ADVANCE(26);
      if (lookahead == 'a') ADVANCE(5);
      if (lookahead == 't') ADVANCE(7);
      if (lookahead == 'u') ADVANCE(6);
      if (lookahead == '{') ADVANCE(13);
      if (lookahead == '}') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(28);
      END_STATE();
    case 1:
      if (lookahead == ',') ADVANCE(14);
      if (lookahead == '<') ADVANCE(19);
      if (lookahead == '>') ADVANCE(20);
      if (lookahead == '}') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(28);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 2:
      if (lookahead == 'e') ADVANCE(9);
      END_STATE();
    case 3:
      if (lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 4:
      if (lookahead == 'p') ADVANCE(3);
      END_STATE();
    case 5:
      if (lookahead == 's') ADVANCE(11);
      END_STATE();
    case 6:
      if (lookahead == 's') ADVANCE(2);
      END_STATE();
    case 7:
      if (lookahead == 'y') ADVANCE(4);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_use);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_as);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(24);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_type);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_module_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_definition_comment);
      if (lookahead == '/') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(23);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_definition_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '/') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(25);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym__discard_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym__name);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym__upname);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 1},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 1},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 1},
  [65] = {.lex_state = 1},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 1},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 1},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_use] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_type] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [sym_module_comment] = ACTIONS(1),
    [sym_definition_comment] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym__discard_name] = ACTIONS(1),
    [sym__upname] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(71),
    [sym__definition] = STATE(4),
    [sym_import] = STATE(4),
    [sym_type_alias] = STATE(4),
    [sym_type_struct] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_use] = ACTIONS(5),
    [anon_sym_type] = ACTIONS(7),
    [sym_module_comment] = ACTIONS(9),
    [sym_definition_comment] = ACTIONS(11),
    [sym_comment] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(15), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(13), 11,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_as,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_type,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
      sym_module_comment,
  [18] = 2,
    ACTIONS(19), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(17), 9,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_as,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_type,
      anon_sym_COLON,
      anon_sym_GT,
      sym_module_comment,
  [34] = 6,
    ACTIONS(5), 1,
      anon_sym_use,
    ACTIONS(7), 1,
      anon_sym_type,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(23), 1,
      sym_module_comment,
    ACTIONS(25), 2,
      sym_definition_comment,
      sym_comment,
    STATE(6), 5,
      sym__definition,
      sym_import,
      sym_type_alias,
      sym_type_struct,
      aux_sym_source_file_repeat1,
  [58] = 3,
    ACTIONS(29), 1,
      anon_sym_LT,
    ACTIONS(31), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(27), 8,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_type,
      anon_sym_EQ,
      anon_sym_GT,
      sym_module_comment,
  [76] = 6,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    ACTIONS(35), 1,
      anon_sym_use,
    ACTIONS(38), 1,
      anon_sym_type,
    ACTIONS(41), 1,
      sym_module_comment,
    ACTIONS(44), 2,
      sym_definition_comment,
      sym_comment,
    STATE(6), 5,
      sym__definition,
      sym_import,
      sym_type_alias,
      sym_type_struct,
      aux_sym_source_file_repeat1,
  [100] = 2,
    ACTIONS(49), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(47), 8,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_type,
      anon_sym_EQ,
      anon_sym_GT,
      sym_module_comment,
  [115] = 4,
    ACTIONS(53), 1,
      anon_sym_SLASH,
    STATE(8), 1,
      aux_sym_module_repeat1,
    ACTIONS(56), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(51), 6,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_DOT,
      anon_sym_as,
      anon_sym_type,
      sym_module_comment,
  [134] = 4,
    ACTIONS(60), 1,
      anon_sym_SLASH,
    STATE(11), 1,
      aux_sym_module_repeat1,
    ACTIONS(62), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(58), 6,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_DOT,
      anon_sym_as,
      anon_sym_type,
      sym_module_comment,
  [153] = 2,
    ACTIONS(66), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(64), 8,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_type,
      anon_sym_EQ,
      anon_sym_GT,
      sym_module_comment,
  [168] = 4,
    ACTIONS(60), 1,
      anon_sym_SLASH,
    STATE(8), 1,
      aux_sym_module_repeat1,
    ACTIONS(70), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(68), 6,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_DOT,
      anon_sym_as,
      anon_sym_type,
      sym_module_comment,
  [187] = 2,
    ACTIONS(74), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(72), 8,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_type,
      anon_sym_EQ,
      anon_sym_GT,
      sym_module_comment,
  [202] = 2,
    ACTIONS(56), 3,
      anon_sym_SLASH,
      sym_definition_comment,
      sym_comment,
    ACTIONS(51), 6,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_DOT,
      anon_sym_as,
      anon_sym_type,
      sym_module_comment,
  [216] = 4,
    ACTIONS(78), 1,
      anon_sym_DOT,
    ACTIONS(80), 1,
      anon_sym_as,
    ACTIONS(82), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(76), 4,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_type,
      sym_module_comment,
  [233] = 2,
    ACTIONS(86), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(84), 5,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_as,
      anon_sym_type,
      sym_module_comment,
  [245] = 2,
    ACTIONS(90), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(88), 5,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_as,
      anon_sym_type,
      sym_module_comment,
  [257] = 6,
    ACTIONS(92), 1,
      anon_sym_GT,
    ACTIONS(94), 1,
      sym__name,
    ACTIONS(96), 1,
      sym__upname,
    STATE(5), 1,
      sym_type_identifier,
    STATE(61), 1,
      sym_type_argument,
    STATE(39), 2,
      sym_type_definition,
      sym_identifier,
  [277] = 6,
    ACTIONS(94), 1,
      sym__name,
    ACTIONS(96), 1,
      sym__upname,
    ACTIONS(98), 1,
      anon_sym_GT,
    STATE(5), 1,
      sym_type_identifier,
    STATE(61), 1,
      sym_type_argument,
    STATE(39), 2,
      sym_type_definition,
      sym_identifier,
  [297] = 6,
    ACTIONS(94), 1,
      sym__name,
    ACTIONS(96), 1,
      sym__upname,
    ACTIONS(100), 1,
      anon_sym_GT,
    STATE(5), 1,
      sym_type_identifier,
    STATE(61), 1,
      sym_type_argument,
    STATE(39), 2,
      sym_type_definition,
      sym_identifier,
  [317] = 2,
    ACTIONS(104), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(102), 5,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_as,
      anon_sym_type,
      sym_module_comment,
  [329] = 2,
    ACTIONS(108), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(106), 5,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_as,
      anon_sym_type,
      sym_module_comment,
  [341] = 3,
    ACTIONS(112), 1,
      anon_sym_as,
    ACTIONS(114), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(110), 4,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_type,
      sym_module_comment,
  [355] = 6,
    ACTIONS(94), 1,
      sym__name,
    ACTIONS(96), 1,
      sym__upname,
    ACTIONS(116), 1,
      anon_sym_GT,
    STATE(5), 1,
      sym_type_identifier,
    STATE(61), 1,
      sym_type_argument,
    STATE(39), 2,
      sym_type_definition,
      sym_identifier,
  [375] = 5,
    ACTIONS(118), 1,
      sym__name,
    ACTIONS(120), 1,
      sym__upname,
    STATE(40), 1,
      sym_type_identifier,
    STATE(66), 1,
      sym_type_argument,
    STATE(39), 2,
      sym_type_definition,
      sym_identifier,
  [392] = 5,
    ACTIONS(94), 1,
      sym__name,
    ACTIONS(96), 1,
      sym__upname,
    STATE(5), 1,
      sym_type_identifier,
    STATE(48), 1,
      sym_type_argument,
    STATE(39), 2,
      sym_type_definition,
      sym_identifier,
  [409] = 5,
    ACTIONS(94), 1,
      sym__name,
    ACTIONS(96), 1,
      sym__upname,
    STATE(5), 1,
      sym_type_identifier,
    STATE(47), 1,
      sym_type_argument,
    STATE(39), 2,
      sym_type_definition,
      sym_identifier,
  [426] = 2,
    ACTIONS(124), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(122), 4,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_type,
      sym_module_comment,
  [437] = 5,
    ACTIONS(94), 1,
      sym__name,
    ACTIONS(96), 1,
      sym__upname,
    STATE(5), 1,
      sym_type_identifier,
    STATE(61), 1,
      sym_type_argument,
    STATE(39), 2,
      sym_type_definition,
      sym_identifier,
  [454] = 2,
    ACTIONS(128), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(126), 4,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_type,
      sym_module_comment,
  [465] = 6,
    ACTIONS(94), 1,
      sym__name,
    ACTIONS(96), 1,
      sym__upname,
    ACTIONS(130), 1,
      anon_sym_RBRACE,
    STATE(51), 1,
      sym_identifier,
    STATE(53), 1,
      sym_type_identifier,
    STATE(55), 1,
      sym_unqualified_import,
  [484] = 2,
    ACTIONS(134), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(132), 4,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_type,
      sym_module_comment,
  [495] = 2,
    ACTIONS(138), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(136), 4,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_type,
      sym_module_comment,
  [506] = 6,
    ACTIONS(94), 1,
      sym__name,
    ACTIONS(96), 1,
      sym__upname,
    ACTIONS(140), 1,
      anon_sym_RBRACE,
    STATE(51), 1,
      sym_identifier,
    STATE(53), 1,
      sym_type_identifier,
    STATE(55), 1,
      sym_unqualified_import,
  [525] = 6,
    ACTIONS(94), 1,
      sym__name,
    ACTIONS(96), 1,
      sym__upname,
    ACTIONS(142), 1,
      anon_sym_RBRACE,
    STATE(49), 1,
      sym_unqualified_import,
    STATE(51), 1,
      sym_identifier,
    STATE(53), 1,
      sym_type_identifier,
  [544] = 5,
    ACTIONS(94), 1,
      sym__name,
    ACTIONS(96), 1,
      sym__upname,
    STATE(51), 1,
      sym_identifier,
    STATE(53), 1,
      sym_type_identifier,
    STATE(55), 1,
      sym_unqualified_import,
  [560] = 4,
    ACTIONS(144), 1,
      anon_sym_RBRACE,
    ACTIONS(146), 1,
      sym__name,
    STATE(72), 1,
      sym_identifier,
    STATE(36), 2,
      sym_type_struct_field,
      aux_sym_type_struct_fields_repeat1,
  [574] = 4,
    ACTIONS(94), 1,
      sym__name,
    ACTIONS(149), 1,
      anon_sym_RBRACE,
    STATE(72), 1,
      sym_identifier,
    STATE(36), 2,
      sym_type_struct_field,
      aux_sym_type_struct_fields_repeat1,
  [588] = 4,
    ACTIONS(94), 1,
      sym__name,
    STATE(69), 1,
      sym_type_struct_fields,
    STATE(72), 1,
      sym_identifier,
    STATE(37), 2,
      sym_type_struct_field,
      aux_sym_type_struct_fields_repeat1,
  [602] = 1,
    ACTIONS(151), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_GT,
      sym__name,
  [609] = 2,
    ACTIONS(153), 1,
      anon_sym_LT,
    ACTIONS(27), 2,
      anon_sym_RBRACE,
      sym__name,
  [617] = 3,
    ACTIONS(155), 1,
      anon_sym_COMMA,
    ACTIONS(158), 1,
      anon_sym_RBRACE,
    STATE(41), 1,
      aux_sym_unqualified_imports_repeat1,
  [627] = 3,
    ACTIONS(96), 1,
      sym__upname,
    STATE(5), 1,
      sym_type_identifier,
    STATE(58), 1,
      sym_type_definition,
  [637] = 3,
    ACTIONS(98), 1,
      anon_sym_GT,
    ACTIONS(160), 1,
      anon_sym_COMMA,
    STATE(52), 1,
      aux_sym_type_definition_repeat1,
  [647] = 3,
    ACTIONS(96), 1,
      sym__upname,
    STATE(5), 1,
      sym_type_identifier,
    STATE(29), 1,
      sym_type_definition,
  [657] = 3,
    ACTIONS(140), 1,
      anon_sym_RBRACE,
    ACTIONS(162), 1,
      anon_sym_COMMA,
    STATE(41), 1,
      aux_sym_unqualified_imports_repeat1,
  [667] = 3,
    ACTIONS(116), 1,
      anon_sym_GT,
    ACTIONS(164), 1,
      anon_sym_COMMA,
    STATE(52), 1,
      aux_sym_type_definition_repeat1,
  [677] = 3,
    ACTIONS(166), 1,
      anon_sym_COMMA,
    ACTIONS(168), 1,
      anon_sym_GT,
    STATE(46), 1,
      aux_sym_type_definition_repeat1,
  [687] = 3,
    ACTIONS(170), 1,
      anon_sym_COMMA,
    ACTIONS(172), 1,
      anon_sym_GT,
    STATE(43), 1,
      aux_sym_type_definition_repeat1,
  [697] = 3,
    ACTIONS(174), 1,
      anon_sym_COMMA,
    ACTIONS(176), 1,
      anon_sym_RBRACE,
    STATE(45), 1,
      aux_sym_unqualified_imports_repeat1,
  [707] = 1,
    ACTIONS(13), 3,
      anon_sym_RBRACE,
      anon_sym_LT,
      sym__name,
  [713] = 2,
    ACTIONS(178), 1,
      anon_sym_as,
    ACTIONS(180), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [721] = 3,
    ACTIONS(182), 1,
      anon_sym_COMMA,
    ACTIONS(185), 1,
      anon_sym_GT,
    STATE(52), 1,
      aux_sym_type_definition_repeat1,
  [731] = 2,
    ACTIONS(187), 1,
      anon_sym_as,
    ACTIONS(180), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [739] = 1,
    ACTIONS(189), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [744] = 1,
    ACTIONS(158), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [749] = 2,
    ACTIONS(94), 1,
      sym__name,
    STATE(32), 1,
      sym_identifier,
  [756] = 2,
    ACTIONS(191), 1,
      sym__name,
    STATE(14), 1,
      sym_module,
  [763] = 2,
    ACTIONS(193), 1,
      anon_sym_LBRACE,
    ACTIONS(195), 1,
      anon_sym_EQ,
  [770] = 2,
    ACTIONS(197), 1,
      anon_sym_LBRACE,
    STATE(22), 1,
      sym_unqualified_imports,
  [777] = 2,
    ACTIONS(94), 1,
      sym__name,
    STATE(27), 1,
      sym_identifier,
  [784] = 1,
    ACTIONS(185), 2,
      anon_sym_COMMA,
      anon_sym_GT,
  [789] = 1,
    ACTIONS(17), 2,
      anon_sym_RBRACE,
      sym__name,
  [794] = 1,
    ACTIONS(47), 2,
      anon_sym_RBRACE,
      sym__name,
  [799] = 1,
    ACTIONS(72), 2,
      anon_sym_RBRACE,
      sym__name,
  [804] = 1,
    ACTIONS(64), 2,
      anon_sym_RBRACE,
      sym__name,
  [809] = 1,
    ACTIONS(199), 2,
      anon_sym_RBRACE,
      sym__name,
  [814] = 2,
    ACTIONS(96), 1,
      sym__upname,
    STATE(54), 1,
      sym_type_identifier,
  [821] = 2,
    ACTIONS(94), 1,
      sym__name,
    STATE(54), 1,
      sym_identifier,
  [828] = 1,
    ACTIONS(201), 1,
      anon_sym_RBRACE,
  [832] = 1,
    ACTIONS(203), 1,
      sym__name,
  [836] = 1,
    ACTIONS(205), 1,
      ts_builtin_sym_end,
  [840] = 1,
    ACTIONS(207), 1,
      anon_sym_COLON,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 18,
  [SMALL_STATE(4)] = 34,
  [SMALL_STATE(5)] = 58,
  [SMALL_STATE(6)] = 76,
  [SMALL_STATE(7)] = 100,
  [SMALL_STATE(8)] = 115,
  [SMALL_STATE(9)] = 134,
  [SMALL_STATE(10)] = 153,
  [SMALL_STATE(11)] = 168,
  [SMALL_STATE(12)] = 187,
  [SMALL_STATE(13)] = 202,
  [SMALL_STATE(14)] = 216,
  [SMALL_STATE(15)] = 233,
  [SMALL_STATE(16)] = 245,
  [SMALL_STATE(17)] = 257,
  [SMALL_STATE(18)] = 277,
  [SMALL_STATE(19)] = 297,
  [SMALL_STATE(20)] = 317,
  [SMALL_STATE(21)] = 329,
  [SMALL_STATE(22)] = 341,
  [SMALL_STATE(23)] = 355,
  [SMALL_STATE(24)] = 375,
  [SMALL_STATE(25)] = 392,
  [SMALL_STATE(26)] = 409,
  [SMALL_STATE(27)] = 426,
  [SMALL_STATE(28)] = 437,
  [SMALL_STATE(29)] = 454,
  [SMALL_STATE(30)] = 465,
  [SMALL_STATE(31)] = 484,
  [SMALL_STATE(32)] = 495,
  [SMALL_STATE(33)] = 506,
  [SMALL_STATE(34)] = 525,
  [SMALL_STATE(35)] = 544,
  [SMALL_STATE(36)] = 560,
  [SMALL_STATE(37)] = 574,
  [SMALL_STATE(38)] = 588,
  [SMALL_STATE(39)] = 602,
  [SMALL_STATE(40)] = 609,
  [SMALL_STATE(41)] = 617,
  [SMALL_STATE(42)] = 627,
  [SMALL_STATE(43)] = 637,
  [SMALL_STATE(44)] = 647,
  [SMALL_STATE(45)] = 657,
  [SMALL_STATE(46)] = 667,
  [SMALL_STATE(47)] = 677,
  [SMALL_STATE(48)] = 687,
  [SMALL_STATE(49)] = 697,
  [SMALL_STATE(50)] = 707,
  [SMALL_STATE(51)] = 713,
  [SMALL_STATE(52)] = 721,
  [SMALL_STATE(53)] = 731,
  [SMALL_STATE(54)] = 739,
  [SMALL_STATE(55)] = 744,
  [SMALL_STATE(56)] = 749,
  [SMALL_STATE(57)] = 756,
  [SMALL_STATE(58)] = 763,
  [SMALL_STATE(59)] = 770,
  [SMALL_STATE(60)] = 777,
  [SMALL_STATE(61)] = 784,
  [SMALL_STATE(62)] = 789,
  [SMALL_STATE(63)] = 794,
  [SMALL_STATE(64)] = 799,
  [SMALL_STATE(65)] = 804,
  [SMALL_STATE(66)] = 809,
  [SMALL_STATE(67)] = 814,
  [SMALL_STATE(68)] = 821,
  [SMALL_STATE(69)] = 828,
  [SMALL_STATE(70)] = 832,
  [SMALL_STATE(71)] = 836,
  [SMALL_STATE(72)] = 840,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_identifier, 1),
  [15] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_identifier, 1),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1),
  [19] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_identifier, 1),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_definition, 1),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_definition, 1),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(57),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(42),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(6),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(6),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_definition, 4),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_definition, 4),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_module_repeat1, 2),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_module_repeat1, 2), SHIFT_REPEAT(70),
  [56] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_module_repeat1, 2),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module, 1),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_module, 1),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_definition, 6),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_definition, 6),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module, 2),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_module, 2),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_definition, 5),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_definition, 5),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 2, .production_id = 1),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import, 2, .production_id = 1),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unqualified_imports, 4),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unqualified_imports, 4),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unqualified_imports, 3),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unqualified_imports, 3),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unqualified_imports, 2),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unqualified_imports, 2),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unqualified_imports, 5),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unqualified_imports, 5),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 4, .production_id = 2),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import, 4, .production_id = 2),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 4, .production_id = 3),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import, 4, .production_id = 3),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_alias, 4),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_alias, 4),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_struct, 5),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_struct, 5),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 6, .production_id = 6),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import, 6, .production_id = 6),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_struct_fields_repeat1, 2),
  [146] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_struct_fields_repeat1, 2), SHIFT_REPEAT(3),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_struct_fields, 1),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_argument, 1, .production_id = 4),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [155] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_unqualified_imports_repeat1, 2), SHIFT_REPEAT(35),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_unqualified_imports_repeat1, 2),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unqualified_import, 1, .production_id = 5),
  [182] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_definition_repeat1, 2), SHIFT_REPEAT(28),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_definition_repeat1, 2),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unqualified_import, 3, .production_id = 7),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_struct_field, 3),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [205] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_aiken(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
