#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 89
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 44
#define ALIAS_COUNT 0
#define TOKEN_COUNT 21
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 8

enum {
  anon_sym_use = 1,
  anon_sym_DOT = 2,
  anon_sym_as = 3,
  anon_sym_SLASH = 4,
  anon_sym_LBRACE = 5,
  anon_sym_COMMA = 6,
  anon_sym_RBRACE = 7,
  anon_sym_type = 8,
  anon_sym_EQ = 9,
  anon_sym_LPAREN = 10,
  anon_sym_RPAREN = 11,
  anon_sym_COLON = 12,
  anon_sym_LT = 13,
  anon_sym_GT = 14,
  sym_module_comment = 15,
  sym_definition_comment = 16,
  sym_comment = 17,
  sym__discard_name = 18,
  sym__name = 19,
  sym__upname = 20,
  sym_source_file = 21,
  sym__definition = 22,
  sym_import = 23,
  sym_module = 24,
  sym_unqualified_imports = 25,
  sym_unqualified_import = 26,
  sym_type_alias = 27,
  sym_type_enum = 28,
  sym_type_enum_variant = 29,
  sym_type_struct = 30,
  sym_type_struct_inner = 31,
  sym_type_struct_fields = 32,
  sym_type_struct_field = 33,
  sym_type_definition = 34,
  sym_type_argument = 35,
  sym_identifier = 36,
  sym_type_identifier = 37,
  aux_sym_source_file_repeat1 = 38,
  aux_sym_module_repeat1 = 39,
  aux_sym_unqualified_imports_repeat1 = 40,
  aux_sym_type_enum_repeat1 = 41,
  aux_sym_type_enum_variant_repeat1 = 42,
  aux_sym_type_struct_fields_repeat1 = 43,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_use] = "use",
  [anon_sym_DOT] = ".",
  [anon_sym_as] = "as",
  [anon_sym_SLASH] = "/",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACE] = "}",
  [anon_sym_type] = "type",
  [anon_sym_EQ] = "=",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COLON] = ":",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [sym_module_comment] = "module_comment",
  [sym_definition_comment] = "definition_comment",
  [sym_comment] = "comment",
  [sym__discard_name] = "_discard_name",
  [sym__name] = "_name",
  [sym__upname] = "_upname",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_import] = "import",
  [sym_module] = "module",
  [sym_unqualified_imports] = "unqualified_imports",
  [sym_unqualified_import] = "unqualified_import",
  [sym_type_alias] = "type_alias",
  [sym_type_enum] = "type_enum",
  [sym_type_enum_variant] = "type_enum_variant",
  [sym_type_struct] = "type_struct",
  [sym_type_struct_inner] = "type_struct_inner",
  [sym_type_struct_fields] = "type_struct_fields",
  [sym_type_struct_field] = "type_struct_field",
  [sym_type_definition] = "type_definition",
  [sym_type_argument] = "type_argument",
  [sym_identifier] = "identifier",
  [sym_type_identifier] = "type_identifier",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_module_repeat1] = "module_repeat1",
  [aux_sym_unqualified_imports_repeat1] = "unqualified_imports_repeat1",
  [aux_sym_type_enum_repeat1] = "type_enum_repeat1",
  [aux_sym_type_enum_variant_repeat1] = "type_enum_variant_repeat1",
  [aux_sym_type_struct_fields_repeat1] = "type_struct_fields_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_use] = anon_sym_use,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_as] = anon_sym_as,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_type] = anon_sym_type,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [sym_module_comment] = sym_module_comment,
  [sym_definition_comment] = sym_definition_comment,
  [sym_comment] = sym_comment,
  [sym__discard_name] = sym__discard_name,
  [sym__name] = sym__name,
  [sym__upname] = sym__upname,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_import] = sym_import,
  [sym_module] = sym_module,
  [sym_unqualified_imports] = sym_unqualified_imports,
  [sym_unqualified_import] = sym_unqualified_import,
  [sym_type_alias] = sym_type_alias,
  [sym_type_enum] = sym_type_enum,
  [sym_type_enum_variant] = sym_type_enum_variant,
  [sym_type_struct] = sym_type_struct,
  [sym_type_struct_inner] = sym_type_struct_inner,
  [sym_type_struct_fields] = sym_type_struct_fields,
  [sym_type_struct_field] = sym_type_struct_field,
  [sym_type_definition] = sym_type_definition,
  [sym_type_argument] = sym_type_argument,
  [sym_identifier] = sym_identifier,
  [sym_type_identifier] = sym_type_identifier,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_module_repeat1] = aux_sym_module_repeat1,
  [aux_sym_unqualified_imports_repeat1] = aux_sym_unqualified_imports_repeat1,
  [aux_sym_type_enum_repeat1] = aux_sym_type_enum_repeat1,
  [aux_sym_type_enum_variant_repeat1] = aux_sym_type_enum_variant_repeat1,
  [aux_sym_type_struct_fields_repeat1] = aux_sym_type_struct_fields_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_use] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_module_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_definition_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__discard_name] = {
    .visible = false,
    .named = true,
  },
  [sym__name] = {
    .visible = false,
    .named = true,
  },
  [sym__upname] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_import] = {
    .visible = true,
    .named = true,
  },
  [sym_module] = {
    .visible = true,
    .named = true,
  },
  [sym_unqualified_imports] = {
    .visible = true,
    .named = true,
  },
  [sym_unqualified_import] = {
    .visible = true,
    .named = true,
  },
  [sym_type_alias] = {
    .visible = true,
    .named = true,
  },
  [sym_type_enum] = {
    .visible = true,
    .named = true,
  },
  [sym_type_enum_variant] = {
    .visible = true,
    .named = true,
  },
  [sym_type_struct] = {
    .visible = true,
    .named = true,
  },
  [sym_type_struct_inner] = {
    .visible = true,
    .named = true,
  },
  [sym_type_struct_fields] = {
    .visible = true,
    .named = true,
  },
  [sym_type_struct_field] = {
    .visible = true,
    .named = true,
  },
  [sym_type_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_type_argument] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_type_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_module_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_unqualified_imports_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_enum_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_enum_variant_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_struct_fields_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_alias = 1,
  field_module = 2,
  field_name = 3,
  field_type_argument = 4,
  field_unqualified = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_alias] = "alias",
  [field_module] = "module",
  [field_name] = "name",
  [field_type_argument] = "type_argument",
  [field_unqualified] = "unqualified",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 1},
  [5] = {.index = 6, .length = 1},
  [6] = {.index = 7, .length = 3},
  [7] = {.index = 10, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_module, 1},
  [1] =
    {field_module, 1},
    {field_unqualified, 3},
  [3] =
    {field_alias, 3},
    {field_module, 1},
  [5] =
    {field_type_argument, 0},
  [6] =
    {field_name, 0},
  [7] =
    {field_alias, 5},
    {field_module, 1},
    {field_unqualified, 3},
  [10] =
    {field_alias, 2},
    {field_name, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 20,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 25,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 32,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 54,
  [56] = 56,
  [57] = 57,
  [58] = 3,
  [59] = 2,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 57,
  [66] = 7,
  [67] = 8,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 4,
  [81] = 81,
  [82] = 82,
  [83] = 10,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      if (lookahead == '(') ADVANCE(18);
      if (lookahead == ')') ADVANCE(19);
      if (lookahead == ',') ADVANCE(14);
      if (lookahead == '.') ADVANCE(10);
      if (lookahead == '/') ADVANCE(12);
      if (lookahead == ':') ADVANCE(20);
      if (lookahead == '<') ADVANCE(21);
      if (lookahead == '=') ADVANCE(17);
      if (lookahead == '>') ADVANCE(22);
      if (lookahead == '_') ADVANCE(28);
      if (lookahead == 'a') ADVANCE(5);
      if (lookahead == 't') ADVANCE(7);
      if (lookahead == 'u') ADVANCE(6);
      if (lookahead == '{') ADVANCE(13);
      if (lookahead == '}') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(30);
      END_STATE();
    case 1:
      if (lookahead == ')') ADVANCE(19);
      if (lookahead == ',') ADVANCE(14);
      if (lookahead == '<') ADVANCE(21);
      if (lookahead == '>') ADVANCE(22);
      if (lookahead == '}') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(30);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 2:
      if (lookahead == 'e') ADVANCE(9);
      END_STATE();
    case 3:
      if (lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 4:
      if (lookahead == 'p') ADVANCE(3);
      END_STATE();
    case 5:
      if (lookahead == 's') ADVANCE(11);
      END_STATE();
    case 6:
      if (lookahead == 's') ADVANCE(2);
      END_STATE();
    case 7:
      if (lookahead == 'y') ADVANCE(4);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_use);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_as);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(26);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_type);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_module_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_definition_comment);
      if (lookahead == '/') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(25);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_definition_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '/') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym__discard_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym__name);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym__upname);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 1},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 1},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 1},
  [71] = {.lex_state = 1},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 1},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 1},
  [81] = {.lex_state = 1},
  [82] = {.lex_state = 1},
  [83] = {.lex_state = 1},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 1},
  [88] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_use] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_type] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [sym_module_comment] = ACTIONS(1),
    [sym_definition_comment] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym__discard_name] = ACTIONS(1),
    [sym__upname] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(85),
    [sym__definition] = STATE(5),
    [sym_import] = STATE(5),
    [sym_type_alias] = STATE(5),
    [sym_type_enum] = STATE(5),
    [sym_type_struct] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_use] = ACTIONS(5),
    [anon_sym_type] = ACTIONS(7),
    [sym_module_comment] = ACTIONS(9),
    [sym_definition_comment] = ACTIONS(11),
    [sym_comment] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(15), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(13), 14,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_as,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_type,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      sym_module_comment,
      sym__upname,
  [21] = 3,
    ACTIONS(19), 1,
      anon_sym_LT,
    ACTIONS(21), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(17), 9,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_type,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_GT,
      sym_module_comment,
  [40] = 2,
    ACTIONS(25), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(23), 10,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_as,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_type,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_GT,
      sym_module_comment,
  [57] = 6,
    ACTIONS(5), 1,
      anon_sym_use,
    ACTIONS(7), 1,
      anon_sym_type,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    ACTIONS(29), 1,
      sym_module_comment,
    ACTIONS(31), 2,
      sym_definition_comment,
      sym_comment,
    STATE(6), 6,
      sym__definition,
      sym_import,
      sym_type_alias,
      sym_type_enum,
      sym_type_struct,
      aux_sym_source_file_repeat1,
  [82] = 6,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    ACTIONS(35), 1,
      anon_sym_use,
    ACTIONS(38), 1,
      anon_sym_type,
    ACTIONS(41), 1,
      sym_module_comment,
    ACTIONS(44), 2,
      sym_definition_comment,
      sym_comment,
    STATE(6), 6,
      sym__definition,
      sym_import,
      sym_type_alias,
      sym_type_enum,
      sym_type_struct,
      aux_sym_source_file_repeat1,
  [107] = 2,
    ACTIONS(49), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(47), 9,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_type,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_GT,
      sym_module_comment,
  [123] = 2,
    ACTIONS(53), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(51), 9,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_type,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_GT,
      sym_module_comment,
  [139] = 9,
    ACTIONS(55), 1,
      sym__name,
    ACTIONS(57), 1,
      sym__upname,
    STATE(44), 1,
      sym_type_identifier,
    STATE(77), 1,
      sym_type_struct_inner,
    STATE(84), 1,
      sym_type_definition,
    STATE(86), 1,
      sym_type_struct_fields,
    STATE(88), 1,
      sym_identifier,
    STATE(27), 2,
      sym_type_enum_variant,
      aux_sym_type_enum_repeat1,
    STATE(45), 2,
      sym_type_struct_field,
      aux_sym_type_struct_fields_repeat1,
  [169] = 2,
    ACTIONS(61), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(59), 9,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_type,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_GT,
      sym_module_comment,
  [185] = 4,
    ACTIONS(65), 1,
      anon_sym_SLASH,
    STATE(11), 1,
      aux_sym_module_repeat1,
    ACTIONS(68), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(63), 6,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_DOT,
      anon_sym_as,
      anon_sym_type,
      sym_module_comment,
  [204] = 4,
    ACTIONS(72), 1,
      anon_sym_SLASH,
    STATE(11), 1,
      aux_sym_module_repeat1,
    ACTIONS(74), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(70), 6,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_DOT,
      anon_sym_as,
      anon_sym_type,
      sym_module_comment,
  [223] = 4,
    ACTIONS(72), 1,
      anon_sym_SLASH,
    STATE(12), 1,
      aux_sym_module_repeat1,
    ACTIONS(78), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(76), 6,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_DOT,
      anon_sym_as,
      anon_sym_type,
      sym_module_comment,
  [242] = 2,
    ACTIONS(68), 3,
      anon_sym_SLASH,
      sym_definition_comment,
      sym_comment,
    ACTIONS(63), 6,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_DOT,
      anon_sym_as,
      anon_sym_type,
      sym_module_comment,
  [256] = 4,
    ACTIONS(82), 1,
      anon_sym_DOT,
    ACTIONS(84), 1,
      anon_sym_as,
    ACTIONS(86), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(80), 4,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_type,
      sym_module_comment,
  [273] = 2,
    ACTIONS(90), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(88), 6,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_RBRACE,
      anon_sym_type,
      sym_module_comment,
      sym__upname,
  [286] = 2,
    ACTIONS(94), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(92), 5,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_as,
      anon_sym_type,
      sym_module_comment,
  [298] = 6,
    ACTIONS(55), 1,
      sym__name,
    ACTIONS(57), 1,
      sym__upname,
    ACTIONS(96), 1,
      anon_sym_RPAREN,
    STATE(3), 1,
      sym_type_identifier,
    STATE(61), 1,
      sym_type_argument,
    STATE(46), 2,
      sym_type_definition,
      sym_identifier,
  [318] = 2,
    ACTIONS(100), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(98), 5,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_as,
      anon_sym_type,
      sym_module_comment,
  [330] = 6,
    ACTIONS(55), 1,
      sym__name,
    ACTIONS(57), 1,
      sym__upname,
    ACTIONS(102), 1,
      anon_sym_GT,
    STATE(3), 1,
      sym_type_identifier,
    STATE(61), 1,
      sym_type_argument,
    STATE(46), 2,
      sym_type_definition,
      sym_identifier,
  [350] = 6,
    ACTIONS(55), 1,
      sym__name,
    ACTIONS(57), 1,
      sym__upname,
    ACTIONS(104), 1,
      anon_sym_GT,
    STATE(3), 1,
      sym_type_identifier,
    STATE(61), 1,
      sym_type_argument,
    STATE(46), 2,
      sym_type_definition,
      sym_identifier,
  [370] = 2,
    ACTIONS(108), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(106), 5,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_as,
      anon_sym_type,
      sym_module_comment,
  [382] = 3,
    ACTIONS(112), 1,
      anon_sym_as,
    ACTIONS(114), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(110), 4,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_type,
      sym_module_comment,
  [396] = 6,
    ACTIONS(55), 1,
      sym__name,
    ACTIONS(57), 1,
      sym__upname,
    ACTIONS(116), 1,
      anon_sym_RPAREN,
    STATE(3), 1,
      sym_type_identifier,
    STATE(61), 1,
      sym_type_argument,
    STATE(46), 2,
      sym_type_definition,
      sym_identifier,
  [416] = 6,
    ACTIONS(55), 1,
      sym__name,
    ACTIONS(57), 1,
      sym__upname,
    ACTIONS(118), 1,
      anon_sym_GT,
    STATE(3), 1,
      sym_type_identifier,
    STATE(61), 1,
      sym_type_argument,
    STATE(46), 2,
      sym_type_definition,
      sym_identifier,
  [436] = 6,
    ACTIONS(120), 1,
      anon_sym_RBRACE,
    ACTIONS(122), 1,
      sym__upname,
    STATE(44), 1,
      sym_type_identifier,
    STATE(77), 1,
      sym_type_struct_inner,
    STATE(84), 1,
      sym_type_definition,
    STATE(26), 2,
      sym_type_enum_variant,
      aux_sym_type_enum_repeat1,
  [456] = 6,
    ACTIONS(57), 1,
      sym__upname,
    ACTIONS(125), 1,
      anon_sym_RBRACE,
    STATE(44), 1,
      sym_type_identifier,
    STATE(77), 1,
      sym_type_struct_inner,
    STATE(84), 1,
      sym_type_definition,
    STATE(26), 2,
      sym_type_enum_variant,
      aux_sym_type_enum_repeat1,
  [476] = 6,
    ACTIONS(55), 1,
      sym__name,
    ACTIONS(57), 1,
      sym__upname,
    ACTIONS(127), 1,
      anon_sym_GT,
    STATE(3), 1,
      sym_type_identifier,
    STATE(61), 1,
      sym_type_argument,
    STATE(46), 2,
      sym_type_definition,
      sym_identifier,
  [496] = 2,
    ACTIONS(131), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(129), 5,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_as,
      anon_sym_type,
      sym_module_comment,
  [508] = 5,
    ACTIONS(55), 1,
      sym__name,
    ACTIONS(57), 1,
      sym__upname,
    STATE(3), 1,
      sym_type_identifier,
    STATE(60), 1,
      sym_type_argument,
    STATE(46), 2,
      sym_type_definition,
      sym_identifier,
  [525] = 2,
    ACTIONS(135), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(133), 4,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_type,
      sym_module_comment,
  [536] = 5,
    ACTIONS(55), 1,
      sym__name,
    ACTIONS(57), 1,
      sym__upname,
    STATE(3), 1,
      sym_type_identifier,
    STATE(57), 1,
      sym_type_argument,
    STATE(46), 2,
      sym_type_definition,
      sym_identifier,
  [553] = 2,
    ACTIONS(139), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(137), 4,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_type,
      sym_module_comment,
  [564] = 5,
    ACTIONS(55), 1,
      sym__name,
    ACTIONS(57), 1,
      sym__upname,
    STATE(3), 1,
      sym_type_identifier,
    STATE(61), 1,
      sym_type_argument,
    STATE(46), 2,
      sym_type_definition,
      sym_identifier,
  [581] = 6,
    ACTIONS(55), 1,
      sym__name,
    ACTIONS(57), 1,
      sym__upname,
    ACTIONS(141), 1,
      anon_sym_RBRACE,
    STATE(63), 1,
      sym_identifier,
    STATE(64), 1,
      sym_type_identifier,
    STATE(72), 1,
      sym_unqualified_import,
  [600] = 2,
    ACTIONS(145), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(143), 4,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_type,
      sym_module_comment,
  [611] = 5,
    ACTIONS(147), 1,
      sym__name,
    ACTIONS(149), 1,
      sym__upname,
    STATE(58), 1,
      sym_type_identifier,
    STATE(73), 1,
      sym_type_argument,
    STATE(46), 2,
      sym_type_definition,
      sym_identifier,
  [628] = 2,
    ACTIONS(153), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(151), 4,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_type,
      sym_module_comment,
  [639] = 6,
    ACTIONS(55), 1,
      sym__name,
    ACTIONS(57), 1,
      sym__upname,
    ACTIONS(155), 1,
      anon_sym_RBRACE,
    STATE(63), 1,
      sym_identifier,
    STATE(64), 1,
      sym_type_identifier,
    STATE(72), 1,
      sym_unqualified_import,
  [658] = 6,
    ACTIONS(55), 1,
      sym__name,
    ACTIONS(57), 1,
      sym__upname,
    ACTIONS(157), 1,
      anon_sym_RBRACE,
    STATE(53), 1,
      sym_unqualified_import,
    STATE(63), 1,
      sym_identifier,
    STATE(64), 1,
      sym_type_identifier,
  [677] = 5,
    ACTIONS(55), 1,
      sym__name,
    ACTIONS(57), 1,
      sym__upname,
    STATE(3), 1,
      sym_type_identifier,
    STATE(65), 1,
      sym_type_argument,
    STATE(46), 2,
      sym_type_definition,
      sym_identifier,
  [694] = 2,
    ACTIONS(161), 2,
      sym_definition_comment,
      sym_comment,
    ACTIONS(159), 4,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_type,
      sym_module_comment,
  [705] = 5,
    ACTIONS(55), 1,
      sym__name,
    ACTIONS(57), 1,
      sym__upname,
    STATE(63), 1,
      sym_identifier,
    STATE(64), 1,
      sym_type_identifier,
    STATE(72), 1,
      sym_unqualified_import,
  [721] = 4,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_LT,
    ACTIONS(165), 1,
      anon_sym_LPAREN,
    ACTIONS(163), 2,
      anon_sym_RBRACE,
      sym__upname,
  [735] = 4,
    ACTIONS(55), 1,
      sym__name,
    ACTIONS(167), 1,
      anon_sym_RBRACE,
    STATE(88), 1,
      sym_identifier,
    STATE(47), 2,
      sym_type_struct_field,
      aux_sym_type_struct_fields_repeat1,
  [749] = 1,
    ACTIONS(169), 5,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_GT,
      sym__name,
  [757] = 4,
    ACTIONS(171), 1,
      anon_sym_RBRACE,
    ACTIONS(173), 1,
      sym__name,
    STATE(88), 1,
      sym_identifier,
    STATE(47), 2,
      sym_type_struct_field,
      aux_sym_type_struct_fields_repeat1,
  [771] = 4,
    ACTIONS(55), 1,
      sym__name,
    STATE(86), 1,
      sym_type_struct_fields,
    STATE(88), 1,
      sym_identifier,
    STATE(45), 2,
      sym_type_struct_field,
      aux_sym_type_struct_fields_repeat1,
  [785] = 3,
    ACTIONS(176), 1,
      anon_sym_COMMA,
    STATE(49), 1,
      aux_sym_type_enum_variant_repeat1,
    ACTIONS(179), 2,
      anon_sym_RPAREN,
      anon_sym_GT,
  [796] = 4,
    ACTIONS(57), 1,
      sym__upname,
    STATE(3), 1,
      sym_type_identifier,
    STATE(33), 1,
      sym_type_struct_inner,
    STATE(78), 1,
      sym_type_definition,
  [809] = 3,
    ACTIONS(181), 1,
      anon_sym_COMMA,
    ACTIONS(184), 1,
      anon_sym_RBRACE,
    STATE(51), 1,
      aux_sym_unqualified_imports_repeat1,
  [819] = 3,
    ACTIONS(96), 1,
      anon_sym_RPAREN,
    ACTIONS(186), 1,
      anon_sym_COMMA,
    STATE(49), 1,
      aux_sym_type_enum_variant_repeat1,
  [829] = 3,
    ACTIONS(188), 1,
      anon_sym_COMMA,
    ACTIONS(190), 1,
      anon_sym_RBRACE,
    STATE(56), 1,
      aux_sym_unqualified_imports_repeat1,
  [839] = 3,
    ACTIONS(127), 1,
      anon_sym_GT,
    ACTIONS(192), 1,
      anon_sym_COMMA,
    STATE(49), 1,
      aux_sym_type_enum_variant_repeat1,
  [849] = 3,
    ACTIONS(118), 1,
      anon_sym_GT,
    ACTIONS(194), 1,
      anon_sym_COMMA,
    STATE(49), 1,
      aux_sym_type_enum_variant_repeat1,
  [859] = 3,
    ACTIONS(155), 1,
      anon_sym_RBRACE,
    ACTIONS(196), 1,
      anon_sym_COMMA,
    STATE(51), 1,
      aux_sym_unqualified_imports_repeat1,
  [869] = 3,
    ACTIONS(198), 1,
      anon_sym_COMMA,
    ACTIONS(200), 1,
      anon_sym_GT,
    STATE(54), 1,
      aux_sym_type_enum_variant_repeat1,
  [879] = 2,
    ACTIONS(202), 1,
      anon_sym_LT,
    ACTIONS(17), 2,
      anon_sym_RBRACE,
      sym__name,
  [887] = 1,
    ACTIONS(13), 3,
      anon_sym_RBRACE,
      anon_sym_LT,
      sym__name,
  [893] = 3,
    ACTIONS(204), 1,
      anon_sym_COMMA,
    ACTIONS(206), 1,
      anon_sym_RPAREN,
    STATE(52), 1,
      aux_sym_type_enum_variant_repeat1,
  [903] = 1,
    ACTIONS(179), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_GT,
  [909] = 3,
    ACTIONS(57), 1,
      sym__upname,
    STATE(3), 1,
      sym_type_identifier,
    STATE(36), 1,
      sym_type_definition,
  [919] = 2,
    ACTIONS(208), 1,
      anon_sym_as,
    ACTIONS(210), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [927] = 2,
    ACTIONS(212), 1,
      anon_sym_as,
    ACTIONS(210), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [935] = 3,
    ACTIONS(214), 1,
      anon_sym_COMMA,
    ACTIONS(216), 1,
      anon_sym_GT,
    STATE(55), 1,
      aux_sym_type_enum_variant_repeat1,
  [945] = 1,
    ACTIONS(47), 2,
      anon_sym_RBRACE,
      sym__name,
  [950] = 1,
    ACTIONS(51), 2,
      anon_sym_RBRACE,
      sym__name,
  [955] = 2,
    ACTIONS(218), 1,
      anon_sym_LBRACE,
    STATE(23), 1,
      sym_unqualified_imports,
  [962] = 1,
    ACTIONS(220), 2,
      anon_sym_RBRACE,
      sym__upname,
  [967] = 2,
    ACTIONS(55), 1,
      sym__name,
    STATE(31), 1,
      sym_identifier,
  [974] = 2,
    ACTIONS(222), 1,
      sym__name,
    STATE(15), 1,
      sym_module,
  [981] = 1,
    ACTIONS(184), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [986] = 1,
    ACTIONS(224), 2,
      anon_sym_RBRACE,
      sym__name,
  [991] = 1,
    ACTIONS(226), 2,
      anon_sym_RBRACE,
      sym__upname,
  [996] = 1,
    ACTIONS(228), 2,
      anon_sym_RBRACE,
      sym__upname,
  [1001] = 1,
    ACTIONS(230), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1006] = 1,
    ACTIONS(163), 2,
      anon_sym_RBRACE,
      sym__upname,
  [1011] = 2,
    ACTIONS(232), 1,
      anon_sym_LBRACE,
    ACTIONS(234), 1,
      anon_sym_EQ,
  [1018] = 2,
    ACTIONS(57), 1,
      sym__upname,
    STATE(76), 1,
      sym_type_identifier,
  [1025] = 1,
    ACTIONS(23), 2,
      anon_sym_RBRACE,
      sym__name,
  [1030] = 2,
    ACTIONS(55), 1,
      sym__name,
    STATE(76), 1,
      sym_identifier,
  [1037] = 2,
    ACTIONS(55), 1,
      sym__name,
    STATE(42), 1,
      sym_identifier,
  [1044] = 1,
    ACTIONS(59), 2,
      anon_sym_RBRACE,
      sym__name,
  [1049] = 1,
    ACTIONS(236), 1,
      anon_sym_LBRACE,
  [1053] = 1,
    ACTIONS(238), 1,
      ts_builtin_sym_end,
  [1057] = 1,
    ACTIONS(240), 1,
      anon_sym_RBRACE,
  [1061] = 1,
    ACTIONS(242), 1,
      sym__name,
  [1065] = 1,
    ACTIONS(244), 1,
      anon_sym_COLON,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 21,
  [SMALL_STATE(4)] = 40,
  [SMALL_STATE(5)] = 57,
  [SMALL_STATE(6)] = 82,
  [SMALL_STATE(7)] = 107,
  [SMALL_STATE(8)] = 123,
  [SMALL_STATE(9)] = 139,
  [SMALL_STATE(10)] = 169,
  [SMALL_STATE(11)] = 185,
  [SMALL_STATE(12)] = 204,
  [SMALL_STATE(13)] = 223,
  [SMALL_STATE(14)] = 242,
  [SMALL_STATE(15)] = 256,
  [SMALL_STATE(16)] = 273,
  [SMALL_STATE(17)] = 286,
  [SMALL_STATE(18)] = 298,
  [SMALL_STATE(19)] = 318,
  [SMALL_STATE(20)] = 330,
  [SMALL_STATE(21)] = 350,
  [SMALL_STATE(22)] = 370,
  [SMALL_STATE(23)] = 382,
  [SMALL_STATE(24)] = 396,
  [SMALL_STATE(25)] = 416,
  [SMALL_STATE(26)] = 436,
  [SMALL_STATE(27)] = 456,
  [SMALL_STATE(28)] = 476,
  [SMALL_STATE(29)] = 496,
  [SMALL_STATE(30)] = 508,
  [SMALL_STATE(31)] = 525,
  [SMALL_STATE(32)] = 536,
  [SMALL_STATE(33)] = 553,
  [SMALL_STATE(34)] = 564,
  [SMALL_STATE(35)] = 581,
  [SMALL_STATE(36)] = 600,
  [SMALL_STATE(37)] = 611,
  [SMALL_STATE(38)] = 628,
  [SMALL_STATE(39)] = 639,
  [SMALL_STATE(40)] = 658,
  [SMALL_STATE(41)] = 677,
  [SMALL_STATE(42)] = 694,
  [SMALL_STATE(43)] = 705,
  [SMALL_STATE(44)] = 721,
  [SMALL_STATE(45)] = 735,
  [SMALL_STATE(46)] = 749,
  [SMALL_STATE(47)] = 757,
  [SMALL_STATE(48)] = 771,
  [SMALL_STATE(49)] = 785,
  [SMALL_STATE(50)] = 796,
  [SMALL_STATE(51)] = 809,
  [SMALL_STATE(52)] = 819,
  [SMALL_STATE(53)] = 829,
  [SMALL_STATE(54)] = 839,
  [SMALL_STATE(55)] = 849,
  [SMALL_STATE(56)] = 859,
  [SMALL_STATE(57)] = 869,
  [SMALL_STATE(58)] = 879,
  [SMALL_STATE(59)] = 887,
  [SMALL_STATE(60)] = 893,
  [SMALL_STATE(61)] = 903,
  [SMALL_STATE(62)] = 909,
  [SMALL_STATE(63)] = 919,
  [SMALL_STATE(64)] = 927,
  [SMALL_STATE(65)] = 935,
  [SMALL_STATE(66)] = 945,
  [SMALL_STATE(67)] = 950,
  [SMALL_STATE(68)] = 955,
  [SMALL_STATE(69)] = 962,
  [SMALL_STATE(70)] = 967,
  [SMALL_STATE(71)] = 974,
  [SMALL_STATE(72)] = 981,
  [SMALL_STATE(73)] = 986,
  [SMALL_STATE(74)] = 991,
  [SMALL_STATE(75)] = 996,
  [SMALL_STATE(76)] = 1001,
  [SMALL_STATE(77)] = 1006,
  [SMALL_STATE(78)] = 1011,
  [SMALL_STATE(79)] = 1018,
  [SMALL_STATE(80)] = 1025,
  [SMALL_STATE(81)] = 1030,
  [SMALL_STATE(82)] = 1037,
  [SMALL_STATE(83)] = 1044,
  [SMALL_STATE(84)] = 1049,
  [SMALL_STATE(85)] = 1053,
  [SMALL_STATE(86)] = 1057,
  [SMALL_STATE(87)] = 1061,
  [SMALL_STATE(88)] = 1065,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_identifier, 1),
  [15] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_identifier, 1),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_definition, 1),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [21] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_definition, 1),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1),
  [25] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_identifier, 1),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(71),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(50),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(6),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(6),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_definition, 4),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_definition, 4),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_definition, 5),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_definition, 5),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_definition, 6),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_definition, 6),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_module_repeat1, 2),
  [65] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_module_repeat1, 2), SHIFT_REPEAT(87),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_module_repeat1, 2),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module, 2),
  [72] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_module, 2),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module, 1),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_module, 1),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 2, .production_id = 1),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import, 2, .production_id = 1),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_struct_inner, 4),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_struct_inner, 4),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unqualified_imports, 5),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unqualified_imports, 5),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unqualified_imports, 4),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unqualified_imports, 4),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unqualified_imports, 3),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unqualified_imports, 3),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 4, .production_id = 2),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import, 4, .production_id = 2),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_enum_repeat1, 2),
  [122] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_enum_repeat1, 2), SHIFT_REPEAT(2),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unqualified_imports, 2),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unqualified_imports, 2),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 6, .production_id = 6),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import, 6, .production_id = 6),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_struct, 2),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_struct, 2),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_alias, 4),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_alias, 4),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_enum, 5),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_enum, 5),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 4, .production_id = 3),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import, 4, .production_id = 3),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_enum_variant, 1),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_struct_fields, 1),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_argument, 1, .production_id = 4),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_struct_fields_repeat1, 2),
  [173] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_struct_fields_repeat1, 2), SHIFT_REPEAT(4),
  [176] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_enum_variant_repeat1, 2), SHIFT_REPEAT(34),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_enum_variant_repeat1, 2),
  [181] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_unqualified_imports_repeat1, 2), SHIFT_REPEAT(43),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_unqualified_imports_repeat1, 2),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unqualified_import, 1, .production_id = 5),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_enum_variant, 4),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_struct_field, 3),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_enum_variant, 6),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_enum_variant, 5),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unqualified_import, 3, .production_id = 7),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [238] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_aiken(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
